import type { ProblemSpec } from "./types.js";

export const BATCH_04_SPECS: ProblemSpec[] = [
    {
        num: 76,
        slug: "integer-to-roman",
        title: "Integer to Roman",
        difficulty: "MEDIUM",
        topics: ["math", "strings"],
        inputFormat: "{ num: number }",
        outputFormat: "string",
        constraints: "1 <= num <= 3999",
        hints: ["Use subtractive pairs like 4 -> IV.", "Process values largest to smallest."],
        pythonBody: "def solve(data):\n    num = data.get(\"num\", 0)\n    pairs = [\n        (1000, \"M\"), (900, \"CM\"), (500, \"D\"), (400, \"CD\"),\n        (100, \"C\"), (90, \"XC\"), (50, \"L\"), (40, \"XL\"),\n        (10, \"X\"), (9, \"IX\"), (5, \"V\"), (4, \"IV\"), (1, \"I\"),\n    ]\n    out = []\n    for v, s in pairs:\n        while num >= v:\n            out.append(s)\n            num -= v\n    return \"\".join(out)",
        javaBody: "int num = data.has(\"num\") ? data.get(\"num\").getAsInt() : 0;\nint[] vals = {1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1};\nString[] sym = {\"M\", \"CM\", \"D\", \"CD\", \"C\", \"XC\", \"L\", \"XL\", \"X\", \"IX\", \"V\", \"IV\", \"I\"};\nStringBuilder sb = new StringBuilder();\nfor (int k = 0; k < vals.length; k++) {\n    while (num >= vals[k]) { sb.append(sym[k]); num -= vals[k]; }\n}\nreturn sb.toString();",
        cppBody: "int num = data.value(\"num\", 0);\nstd::vector<std::pair<int, std::string>> pairs = {\n    {1000, \"M\"}, {900, \"CM\"}, {500, \"D\"}, {400, \"CD\"},\n    {100, \"C\"}, {90, \"XC\"}, {50, \"L\"}, {40, \"XL\"},\n    {10, \"X\"}, {9, \"IX\"}, {5, \"V\"}, {4, \"IV\"}, {1, \"I\"}\n};\nstd::string out;\nfor (auto [v, s] : pairs) while (num >= v) { out += s; num -= v; }\nreturn out;",
        visibleCases: [
            { input: {"num": 3}, output: "III", explanation: "3 = III" },
            { input: {"num": 4}, output: "IV", explanation: "Subtractive IV" },
        ],
        hiddenCases: [
            { input: {"num": 1}, output: "I" },
            { input: {"num": 9}, output: "IX" },
            { input: {"num": 58}, output: "LVIII" },
            { input: {"num": 1994}, output: "MCMXCIV" },
            { input: {"num": 27}, output: "XXVII" },
            { input: {"num": 3999}, output: "MMMCMXCIX" },
            { input: {"num": 944}, output: "CMXLIV" },
            { input: {"num": 49}, output: "XLIX" },
        ],
    },
    {
        num: 77,
        slug: "powx-n",
        title: "Pow(x, n)",
        difficulty: "MEDIUM",
        topics: ["math", "binary-search"],
        inputFormat: "{ x: number, n: number }",
        outputFormat: "number",
        constraints: "-100.0 <= x <= 100.0; -2^31 <= n <= 2^31 - 1",
        hints: ["Use binary exponentiation.", "Handle negative n by inverting x."],
        pythonBody: "def solve(data):\n    x = data.get(\"x\", 1.0)\n    n = data.get(\"n\", 0)\n    if n < 0:\n        x = 1 / x\n        n = -n\n    ans = 1.0\n    while n:\n        if n & 1:\n            ans *= x\n        x *= x\n        n >>= 1\n    return ans",
        javaBody: "double x = data.has(\"x\") ? data.get(\"x\").getAsDouble() : 1.0;\nlong n = data.has(\"n\") ? data.get(\"n\").getAsLong() : 0;\nif (n < 0) { x = 1.0 / x; n = -n; }\ndouble ans = 1.0;\nwhile (n > 0) {\n    if ((n & 1) == 1) ans *= x;\n    x *= x;\n    n >>= 1;\n}\nreturn ans;",
        cppBody: "double x = data.value(\"x\", 1.0);\nlong long n = data.value(\"n\", 0LL);\nif (n < 0) { x = 1.0 / x; n = -n; }\ndouble ans = 1.0;\nwhile (n > 0) {\n    if (n & 1) ans *= x;\n    x *= x;\n    n >>= 1;\n}\nreturn ans;",
        visibleCases: [
            { input: {"x": 2, "n": 10}, output: 1024, explanation: "2^10" },
            { input: {"x": 2.1, "n": 3}, output: 9.261000000000001 },
        ],
        hiddenCases: [
            { input: {"x": 2, "n": -2}, output: 0.25 },
            { input: {"x": 1, "n": 2147483647}, output: 1 },
            { input: {"x": 2, "n": 0}, output: 1 },
            { input: {"x": 0, "n": 5}, output: 0 },
            { input: {"x": 1, "n": -5}, output: 1 },
            { input: {"x": 3, "n": 4}, output: 81 },
            { input: {"x": 0.5, "n": 3}, output: 0.125 },
            { input: {"x": -2, "n": 3}, output: -8 },
        ],
    },
    {
        num: 78,
        slug: "my-calendar-i",
        title: "My Calendar I",
        difficulty: "MEDIUM",
        topics: ["binary-search", "trees"],
        inputFormat: "{ ops: (\"book\")[], args: [number, number][] }",
        outputFormat: "boolean[] (one per book)",
        constraints: "0 <= start < end <= 10^9; at most 1000 book calls",
        hints: ["Store booked intervals.", "Reject overlap on half-open [start, end)."],
        pythonBody: "def solve(data):\n    ops = data.get(\"ops\", [])\n    args = data.get(\"args\", [])\n    bookings = []\n    out = []\n    for op, a in zip(ops, args):\n        if op != \"book\":\n            continue\n        start, end = a\n        ok = all(not (start < e and end > s) for s, e in bookings)\n        if ok:\n            bookings.append((start, end))\n        out.append(ok)\n    return out",
        javaBody: "JsonArray opsArr = data.has(\"ops\") ? data.getAsJsonArray(\"ops\") : new JsonArray();\nJsonArray argsArr = data.has(\"args\") ? data.getAsJsonArray(\"args\") : new JsonArray();\nList<int[]> bookings = new ArrayList<>();\nList<Boolean> out = new ArrayList<>();\nfor (int i = 0; i < opsArr.size(); i++) {\n    if (!\"book\".equals(opsArr.get(i).getAsString())) continue;\n    JsonArray a = argsArr.get(i).getAsJsonArray();\n    int start = a.get(0).getAsInt();\n    int end = a.get(1).getAsInt();\n    boolean ok = true;\n    for (int[] b : bookings) {\n        if (start < b[1] && end > b[0]) { ok = false; break; }\n    }\n    if (ok) bookings.add(new int[]{start, end});\n    out.add(ok);\n}\nreturn out;",
        cppBody: "std::vector<std::string> ops = data.value(\"ops\", std::vector<std::string>{});\nstd::vector<std::vector<int>> args = data.value(\"args\", std::vector<std::vector<int>>{});\nstd::vector<std::pair<int,int>> bookings;\njson out = json::array();\nfor (size_t i = 0; i < ops.size(); i++) {\n    if (ops[i] != \"book\") continue;\n    int start = args[i][0], end = args[i][1];\n    bool ok = true;\n    for (auto [s,e] : bookings) if (start < e && end > s) { ok = false; break; }\n    if (ok) bookings.push_back({start, end});\n    out.push_back(ok);\n}\nreturn out;",
        visibleCases: [
            { input: {"ops": ["book", "book", "book"], "args": [[10, 20], [15, 25], [20, 30]]}, output: [true, false, true], explanation: "Second overlaps" },
            { input: {"ops": ["book", "book"], "args": [[47, 50], [47, 50]]}, output: [true, false] },
        ],
        hiddenCases: [
            { input: {"ops": ["book"], "args": [[5, 10]]}, output: [true] },
            { input: {"ops": ["book", "book"], "args": [[10, 20], [20, 30]]}, output: [true, true] },
            { input: {"ops": ["book", "book", "book"], "args": [[1, 5], [5, 10], [3, 7]]}, output: [true, true, false] },
            { input: {"ops": ["book", "book"], "args": [[0, 10], [10, 20]]}, output: [true, true] },
            { input: {"ops": ["book", "book", "book"], "args": [[20, 30], [10, 20], [15, 25]]}, output: [true, true, false] },
            { input: {"ops": ["book"], "args": [[1, 1000000]]}, output: [true] },
            { input: {"ops": ["book", "book"], "args": [[1, 2], [2, 3]]}, output: [true, true] },
            { input: {"ops": ["book", "book", "book"], "args": [[5, 15], [10, 20], [12, 18]]}, output: [true, false, false] },
        ],
    },
    {
        num: 79,
        slug: "design-hashmap",
        title: "Design HashMap",
        difficulty: "MEDIUM",
        topics: ["hash-table"],
        inputFormat: "{ ops: (\"put\"|\"get\"|\"remove\")[], args: number[][] }",
        outputFormat: "(number | null)[] (one per get)",
        constraints: "At most 10^4 operations; keys and values in [-10^6, 10^6]",
        hints: ["Use an array of buckets or open addressing.", "Return null when a key is missing."],
        pythonBody: "def solve(data):\n    ops = data.get(\"ops\", [])\n    args = data.get(\"args\", [])\n    m = {}\n    out = []\n    for op, a in zip(ops, args):\n        if op == \"put\":\n            m[a[0]] = a[1]\n        elif op == \"get\":\n            out.append(m.get(a[0]))\n        elif op == \"remove\":\n            m.pop(a[0], None)\n    return out",
        javaBody: "JsonArray opsArr = data.has(\"ops\") ? data.getAsJsonArray(\"ops\") : new JsonArray();\nJsonArray argsArr = data.has(\"args\") ? data.getAsJsonArray(\"args\") : new JsonArray();\nMap<Integer, Integer> map = new HashMap<>();\nList<Integer> out = new ArrayList<>();\nfor (int i = 0; i < opsArr.size(); i++) {\n    String op = opsArr.get(i).getAsString();\n    JsonArray a = argsArr.get(i).getAsJsonArray();\n    if (\"put\".equals(op)) map.put(a.get(0).getAsInt(), a.get(1).getAsInt());\n    else if (\"get\".equals(op)) out.add(map.containsKey(a.get(0).getAsInt()) ? map.get(a.get(0).getAsInt()) : null);\n    else if (\"remove\".equals(op)) map.remove(a.get(0).getAsInt());\n}\nreturn out;",
        cppBody: "std::vector<std::string> ops = data.value(\"ops\", std::vector<std::string>{});\nstd::vector<std::vector<int>> args = data.value(\"args\", std::vector<std::vector<int>>{});\nstd::unordered_map<int, int> map;\njson out = json::array();\nfor (size_t i = 0; i < ops.size(); i++) {\n    if (ops[i] == \"put\") map[args[i][0]] = args[i][1];\n    else if (ops[i] == \"get\") {\n        auto it = map.find(args[i][0]);\n        out.push_back(it == map.end() ? json(nullptr) : json(it->second));\n    } else if (ops[i] == \"remove\") map.erase(args[i][0]);\n}\nreturn out;",
        visibleCases: [
            { input: {"ops": ["put", "get", "put", "get", "remove", "get"], "args": [[1, 1], [1], [2, 2], [2], [1], [2]]}, output: [1, 2, 2], explanation: "Standard get/put/remove" },
            { input: {"ops": ["put", "get", "put", "get", "get", "put", "get", "remove", "get"], "args": [[1, 1], [1], [2, 2], [2], [3], [4, 4], [4], [4], [4]]}, output: [1, 2, null, 4, null] },
        ],
        hiddenCases: [
            { input: {"ops": ["get"], "args": [[1]]}, output: [null] },
            { input: {"ops": ["put", "get"], "args": [[0, 0], [0]]}, output: [0] },
            { input: {"ops": ["put", "put", "get", "get"], "args": [[1, 10], [2, 20], [1], [2]]}, output: [10, 20] },
            { input: {"ops": ["put", "remove", "get"], "args": [[5, 5], [5], [5]]}, output: [null] },
            { input: {"ops": ["put", "put", "remove", "get", "get"], "args": [[1, 1], [2, 2], [1], [1], [2]]}, output: [null, 2] },
            { input: {"ops": ["put", "get", "put", "get"], "args": [[100, 200], [100], [100, 300], [100]]}, output: [200, 300] },
            { input: {"ops": ["put", "remove", "put", "get"], "args": [[7, 7], [7], [7, 8], [7]]}, output: [8] },
            { input: {"ops": ["put", "put", "remove", "remove", "get"], "args": [[1, 1], [2, 2], [1], [2], [2]]}, output: [null] },
        ],
    },
    {
        num: 80,
        slug: "design-add-and-search-words-data-structure",
        title: "Design Add and Search Words Data Structure",
        difficulty: "MEDIUM",
        topics: ["trie", "strings"],
        inputFormat: "{ ops: (\"addWord\"|\"search\")[], args: [string[]] }",
        outputFormat: "boolean[] (one per addWord/search)",
        constraints: "Words are lowercase; at most 10^4 operations",
        hints: ["Build a trie of words.", "Use DFS for '.' wildcard matches."],
        pythonBody: "def solve(data):\n    ops = data.get(\"ops\", [])\n    args = data.get(\"args\", [])\n\n    class Node:\n        __slots__ = (\"ch\", \"end\")\n        def __init__(self):\n            self.ch = {}\n            self.end = False\n\n    root = Node()\n    out = []\n    for op, a in zip(ops, args):\n        if op == \"addWord\":\n            node = root\n            for ch in a[0]:\n                node = node.ch.setdefault(ch, Node())\n            node.end = True\n            out.append(True)\n        else:\n            word = a[0]\n            def dfs(node, i):\n                if i == len(word):\n                    return node.end\n                ch = word[i]\n                if ch == '.':\n                    return any(dfs(c, i + 1) for c in node.ch.values())\n                if ch not in node.ch:\n                    return False\n                return dfs(node.ch[ch], i + 1)\n            out.append(dfs(root, 0))\n    return out",
        javaBody: "JsonArray opsArr = data.has(\"ops\") ? data.getAsJsonArray(\"ops\") : new JsonArray();\nJsonArray argsArr = data.has(\"args\") ? data.getAsJsonArray(\"args\") : new JsonArray();\nclass TNode { Map<Character, TNode> ch = new HashMap<>(); boolean end; }\nTNode root = new TNode();\nList<Boolean> out = new ArrayList<>();\nclass Search {\n    boolean dfs(TNode node, String w, int i) {\n        if (i == w.length()) return node.end;\n        char ch = w.charAt(i);\n        if (ch == '.') {\n            for (TNode child : node.ch.values()) if (dfs(child, w, i + 1)) return true;\n            return false;\n        }\n        TNode next = node.ch.get(ch);\n        return next != null && dfs(next, w, i + 1);\n    }\n}\nSearch search = new Search();\nfor (int i = 0; i < opsArr.size(); i++) {\n    String op = opsArr.get(i).getAsString();\n    String word = argsArr.get(i).getAsJsonArray().get(0).getAsString();\n    if (\"addWord\".equals(op)) {\n        TNode node = root;\n        for (char ch : word.toCharArray()) node = node.ch.computeIfAbsent(ch, k -> new TNode());\n        node.end = true;\n        out.add(true);\n    } else out.add(search.dfs(root, word, 0));\n}\nreturn out;",
        cppBody: "std::vector<std::string> ops = data.value(\"ops\", std::vector<std::string>{});\nstd::vector<std::vector<std::string>> args = data.value(\"args\", std::vector<std::vector<std::string>>{});\nstruct Node { std::unordered_map<char, std::unique_ptr<Node>> ch; bool end = false; };\nNode root;\njson out = json::array();\nstd::function<bool(Node*, const std::string&, int)> dfs;\ndfs = [&](Node* node, const std::string& w, int i) -> bool {\n    if (i == (int)w.size()) return node->end;\n    char ch = w[i];\n    if (ch == '.') {\n        for (auto& [_, child] : node->ch) if (dfs(child.get(), w, i + 1)) return true;\n        return false;\n    }\n    auto it = node->ch.find(ch);\n    if (it == node->ch.end()) return false;\n    return dfs(it->second.get(), w, i + 1);\n};\nfor (size_t i = 0; i < ops.size(); i++) {\n    const std::string& word = args[i][0];\n    if (ops[i] == \"addWord\") {\n        Node* node = &root;\n        for (char ch : word) node = node->ch[ch].get() ? node->ch[ch].get() : (node->ch[ch] = std::make_unique<Node>()).get();\n        node->end = true;\n        out.push_back(true);\n    } else out.push_back(dfs(&root, word, 0));\n}\nreturn out;",
        visibleCases: [
            { input: {"ops": ["addWord", "search", "search", "search", "search"], "args": [["bad"], ["bad"], [".ad"], ["b.."]]}, output: [true, true, true, true], explanation: "Wildcard search" },
            { input: {"ops": ["addWord", "addWord", "search"], "args": [["at"], ["and"], ["an"]]}, output: [true, true, false] },
        ],
        hiddenCases: [
            { input: {"ops": ["addWord", "search"], "args": [["a"], ["."]]}, output: [true, true] },
            { input: {"ops": ["addWord", "search"], "args": [["abc"], ["ab"]]}, output: [true, false] },
            { input: {"ops": ["addWord", "search"], "args": [["abc"], [".bc"]]}, output: [true, true] },
            { input: {"ops": ["addWord", "search"], "args": [["abc"], ["..."]]}, output: [true, true] },
            { input: {"ops": ["addWord", "addWord", "search"], "args": [["hello"], ["hell"], ["he..o"]]}, output: [true, true, true] },
            { input: {"ops": ["addWord", "search"], "args": [["xyz"], ["x.z"]]}, output: [true, true] },
            { input: {"ops": ["addWord", "search"], "args": [["a"], ["a"]]}, output: [true, true] },
            { input: {"ops": ["addWord", "search"], "args": [["dot"], ["d.t"]]}, output: [true, true] },
        ],
    },
    {
        num: 81,
        slug: "trapping-rain-water",
        title: "Trapping Rain Water",
        difficulty: "HARD",
        topics: ["two-pointers", "stack", "arrays"],
        inputFormat: "{ height: number[] }",
        outputFormat: "number",
        constraints: "1 <= height.length <= 2*10^5; 0 <= height[i] <= 10^5",
        hints: ["Use two pointers and running max boundaries.", "Water at index depends on smaller boundary."],
        pythonBody: "def solve(data):\n    h = data.get(\"height\", [])\n    l, r = 0, len(h) - 1\n    left_max = right_max = 0\n    ans = 0\n    while l <= r:\n        if left_max <= right_max:\n            left_max = max(left_max, h[l])\n            ans += left_max - h[l]\n            l += 1\n        else:\n            right_max = max(right_max, h[r])\n            ans += right_max - h[r]\n            r -= 1\n    return ans",
        javaBody: "JsonArray arr = data.has(\"height\") ? data.getAsJsonArray(\"height\") : new JsonArray();\nint n = arr.size();\nint l = 0, r = n - 1, leftMax = 0, rightMax = 0, ans = 0;\nwhile (l <= r) {\n    if (leftMax <= rightMax) {\n        leftMax = Math.max(leftMax, arr.get(l).getAsInt());\n        ans += leftMax - arr.get(l).getAsInt();\n        l++;\n    } else {\n        rightMax = Math.max(rightMax, arr.get(r).getAsInt());\n        ans += rightMax - arr.get(r).getAsInt();\n        r--;\n    }\n}\nreturn ans;",
        cppBody: "std::vector<int> h = data.value(\"height\", std::vector<int>{});\nint l = 0, r = static_cast<int>(h.size()) - 1, leftMax = 0, rightMax = 0, ans = 0;\nwhile (l <= r) {\n    if (leftMax <= rightMax) {\n        leftMax = std::max(leftMax, h[l]);\n        ans += leftMax - h[l++];\n    } else {\n        rightMax = std::max(rightMax, h[r]);\n        ans += rightMax - h[r--];\n    }\n}\nreturn ans;",
        visibleCases: [
            { input: {"height": [0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]}, output: 6, explanation: "Classic trap" },
            { input: {"height": [4, 2, 0, 3, 2, 5]}, output: 9 },
        ],
        hiddenCases: [
            { input: {"height": [1]}, output: 0 },
            { input: {"height": [2, 0, 2]}, output: 2 },
            { input: {"height": [3, 0, 0, 2, 0, 4]}, output: 10 },
            { input: {"height": [1, 2, 3]}, output: 0 },
            { input: {"height": [3, 2, 1]}, output: 0 },
            { input: {"height": [5, 4, 1, 2]}, output: 1 },
            { input: {"height": [2, 1, 0, 1, 3]}, output: 4 },
            { input: {"height": [0, 7, 1, 4, 6]}, output: 7 },
        ],
    },
    {
        num: 82,
        slug: "median-of-two-sorted-arrays",
        title: "Median of Two Sorted Arrays",
        difficulty: "HARD",
        topics: ["binary-search", "arrays"],
        inputFormat: "{ nums1: number[], nums2: number[] }",
        outputFormat: "number",
        constraints: "0 <= m,n <= 10^5; m + n >= 1",
        hints: ["Binary search on smaller array partition.", "Left max <= right min condition."],
        pythonBody: "def solve(data):\n    a = data.get(\"nums1\", [])\n    b = data.get(\"nums2\", [])\n    if len(a) > len(b):\n        a, b = b, a\n    m, n = len(a), len(b)\n    total = m + n\n    half = (total + 1) // 2\n    lo, hi = 0, m\n    while lo <= hi:\n        i = (lo + hi) // 2\n        j = half - i\n        aL = a[i - 1] if i else float(\"-inf\")\n        aR = a[i] if i < m else float(\"inf\")\n        bL = b[j - 1] if j else float(\"-inf\")\n        bR = b[j] if j < n else float(\"inf\")\n        if aL <= bR and bL <= aR:\n            if total % 2:\n                return max(aL, bL)\n            return (max(aL, bL) + min(aR, bR)) / 2\n        if aL > bR:\n            hi = i - 1\n        else:\n            lo = i + 1\n    return 0",
        javaBody: "JsonArray aArr = data.has(\"nums1\") ? data.getAsJsonArray(\"nums1\") : new JsonArray();\nJsonArray bArr = data.has(\"nums2\") ? data.getAsJsonArray(\"nums2\") : new JsonArray();\nint[] a = new int[aArr.size()];\nint[] b = new int[bArr.size()];\nfor (int i = 0; i < a.length; i++) a[i] = aArr.get(i).getAsInt();\nfor (int i = 0; i < b.length; i++) b[i] = bArr.get(i).getAsInt();\nif (a.length > b.length) { int[] t = a; a = b; b = t; }\nint m = a.length, n = b.length, total = m + n, half = (total + 1) / 2;\nint lo = 0, hi = m;\nwhile (lo <= hi) {\n    int i = lo + (hi - lo) / 2, j = half - i;\n    double aL = i > 0 ? a[i - 1] : Double.NEGATIVE_INFINITY;\n    double aR = i < m ? a[i] : Double.POSITIVE_INFINITY;\n    double bL = j > 0 ? b[j - 1] : Double.NEGATIVE_INFINITY;\n    double bR = j < n ? b[j] : Double.POSITIVE_INFINITY;\n    if (aL <= bR && bL <= aR) {\n        if (total % 2 == 1) return Math.max(aL, bL);\n        return (Math.max(aL, bL) + Math.min(aR, bR)) / 2.0;\n    }\n    if (aL > bR) hi = i - 1; else lo = i + 1;\n}\nreturn 0;",
        cppBody: "std::vector<int> a = data.value(\"nums1\", std::vector<int>{});\nstd::vector<int> b = data.value(\"nums2\", std::vector<int>{});\nif (a.size() > b.size()) std::swap(a, b);\nint m = static_cast<int>(a.size()), n = static_cast<int>(b.size());\nint total = m + n, half = (total + 1) / 2, lo = 0, hi = m;\nwhile (lo <= hi) {\n    int i = lo + (hi - lo) / 2, j = half - i;\n    double aL = i > 0 ? a[i - 1] : -1e18, aR = i < m ? a[i] : 1e18;\n    double bL = j > 0 ? b[j - 1] : -1e18, bR = j < n ? b[j] : 1e18;\n    if (aL <= bR && bL <= aR) {\n        if (total % 2 == 1) return std::max(aL, bL);\n        return (std::max(aL, bL) + std::min(aR, bR)) / 2.0;\n    }\n    if (aL > bR) hi = i - 1; else lo = i + 1;\n}\nreturn 0;",
        visibleCases: [
            { input: {"nums1": [1, 3], "nums2": [2]}, output: 2, explanation: "Median is 2" },
            { input: {"nums1": [1, 2], "nums2": [3, 4]}, output: 2.5 },
        ],
        hiddenCases: [
            { input: {"nums1": [], "nums2": [1]}, output: 1 },
            { input: {"nums1": [2], "nums2": []}, output: 2 },
            { input: {"nums1": [0, 0], "nums2": [0, 0]}, output: 0 },
            { input: {"nums1": [1], "nums2": [2, 3, 4]}, output: 2.5 },
            { input: {"nums1": [1, 2, 3], "nums2": [4, 5, 6]}, output: 3.5 },
            { input: {"nums1": [100], "nums2": [1, 2, 3, 4, 5]}, output: 3.5 },
            { input: {"nums1": [1, 3, 8, 9, 15], "nums2": [7, 11, 18, 19, 21, 25]}, output: 11 },
            { input: {"nums1": [23, 26, 31, 35], "nums2": [3, 5, 7, 9, 11, 16]}, output: 13.5 },
        ],
    },
    {
        num: 83,
        slug: "minimum-window-substring",
        title: "Minimum Window Substring",
        difficulty: "HARD",
        topics: ["sliding-window", "hash-table", "strings"],
        inputFormat: "{ s: string, t: string }",
        outputFormat: "string",
        constraints: "1 <= s.length, t.length <= 10^5",
        hints: ["Expand right until window covers t.", "Shrink left while still valid."],
        pythonBody: "def solve(data):\n    from collections import Counter\n    s = data.get(\"s\", \"\")\n    t = data.get(\"t\", \"\")\n    if not t or not s:\n        return \"\"\n    need = Counter(t)\n    missing = len(t)\n    left = start = 0\n    length = float(\"inf\")\n    for right, ch in enumerate(s):\n        if ch in need:\n            if need[ch] > 0:\n                missing -= 1\n            need[ch] -= 1\n        while missing == 0:\n            if right - left + 1 < length:\n                length = right - left + 1\n                start = left\n            if s[left] in need:\n                need[s[left]] += 1\n                if need[s[left]] > 0:\n                    missing += 1\n            left += 1\n    return \"\" if length == float(\"inf\") else s[start:start + length]",
        javaBody: "String s = data.has(\"s\") ? data.get(\"s\").getAsString() : \"\";\nString t = data.has(\"t\") ? data.get(\"t\").getAsString() : \"\";\nif (t.isEmpty() || s.isEmpty()) return \"\";\nMap<Character, Integer> need = new HashMap<>();\nfor (char ch : t.toCharArray()) need.put(ch, need.getOrDefault(ch, 0) + 1);\nint missing = t.length(), left = 0, start = 0, length = Integer.MAX_VALUE;\nfor (int right = 0; right < s.length(); right++) {\n    char ch = s.charAt(right);\n    if (need.containsKey(ch)) {\n        if (need.get(ch) > 0) missing--;\n        need.put(ch, need.get(ch) - 1);\n    }\n    while (missing == 0) {\n        if (right - left + 1 < length) { length = right - left + 1; start = left; }\n        char lc = s.charAt(left);\n        if (need.containsKey(lc)) {\n            need.put(lc, need.get(lc) + 1);\n            if (need.get(lc) > 0) missing++;\n        }\n        left++;\n    }\n}\nreturn length == Integer.MAX_VALUE ? \"\" : s.substring(start, start + length);",
        cppBody: "std::string s = data.value(\"s\", \"\");\nstd::string t = data.value(\"t\", \"\");\nif (t.empty() || s.empty()) return \"\";\nstd::unordered_map<char, int> need;\nfor (char ch : t) need[ch]++;\nint missing = static_cast<int>(t.size()), left = 0, start = 0, length = INT_MAX;\nfor (int right = 0; right < static_cast<int>(s.size()); right++) {\n    char ch = s[right];\n    if (need.count(ch)) {\n        if (need[ch] > 0) missing--;\n        need[ch]--;\n    }\n    while (missing == 0) {\n        if (right - left + 1 < length) { length = right - left + 1; start = left; }\n        char lc = s[left];\n        if (need.count(lc)) {\n            need[lc]++;\n            if (need[lc] > 0) missing++;\n        }\n        left++;\n    }\n}\nreturn length == INT_MAX ? \"\" : s.substr(start, length);",
        visibleCases: [
            { input: {"s": "ADOBECODEBANC", "t": "ABC"}, output: "BANC", explanation: "Smallest window BANC" },
            { input: {"s": "a", "t": "a"}, output: "a" },
        ],
        hiddenCases: [
            { input: {"s": "a", "t": "aa"}, output: "" },
            { input: {"s": "abc", "t": "cba"}, output: "abc" },
            { input: {"s": "abc", "t": "ac"}, output: "abc" },
            { input: {"s": "cabwefgewcwaefgcf", "t": "cae"}, output: "cwae" },
            { input: {"s": "aa", "t": "aa"}, output: "aa" },
            { input: {"s": "bba", "t": "ab"}, output: "ba" },
            { input: {"s": "ab", "t": "b"}, output: "b" },
            { input: {"s": "abc", "t": "d"}, output: "" },
        ],
    },
    {
        num: 84,
        slug: "merge-k-sorted-lists",
        title: "Merge K Sorted Lists",
        difficulty: "HARD",
        topics: ["linked-list", "heap"],
        inputFormat: "{ lists: number[][] }",
        outputFormat: "number[] (merged sorted)",
        constraints: "0 <= lists.length <= 10^4; each list sorted ascending",
        hints: ["Use a min-heap of list heads.", "Pop smallest and advance that list."],
        pythonBody: "def solve(data):\n    import heapq\n    lists = data.get(\"lists\", [])\n    h = []\n    for i, lst in enumerate(lists):\n        if lst:\n            heapq.heappush(h, (lst[0], i, 0))\n    out = []\n    while h:\n        v, li, idx = heapq.heappop(h)\n        out.append(v)\n        if idx + 1 < len(lists[li]):\n            heapq.heappush(h, (lists[li][idx + 1], li, idx + 1))\n    return out",
        javaBody: "JsonArray listsArr = data.has(\"lists\") ? data.getAsJsonArray(\"lists\") : new JsonArray();\nPriorityQueue<int[]> pq = new PriorityQueue<>((a, b) -> Integer.compare(a[0], b[0]));\nfor (int i = 0; i < listsArr.size(); i++) {\n    JsonArray lst = listsArr.get(i).getAsJsonArray();\n    if (lst.size() > 0) pq.offer(new int[]{lst.get(0).getAsInt(), i, 0});\n}\nList<Integer> out = new ArrayList<>();\nwhile (!pq.isEmpty()) {\n    int[] cur = pq.poll();\n    out.add(cur[0]);\n    JsonArray lst = listsArr.get(cur[1]).getAsJsonArray();\n    int next = cur[2] + 1;\n    if (next < lst.size()) pq.offer(new int[]{lst.get(next).getAsInt(), cur[1], next});\n}\nreturn out;",
        cppBody: "std::vector<std::vector<int>> lists = data.value(\"lists\", std::vector<std::vector<int>>{});\nusing T = std::tuple<int,int,int>;\nstd::priority_queue<T, std::vector<T>, std::greater<T>> pq;\nfor (int i = 0; i < static_cast<int>(lists.size()); i++)\n    if (!lists[i].empty()) pq.push({lists[i][0], i, 0});\nstd::vector<int> out;\nwhile (!pq.empty()) {\n    auto [v, li, idx] = pq.top(); pq.pop();\n    out.push_back(v);\n    if (idx + 1 < static_cast<int>(lists[li].size()))\n        pq.push({lists[li][idx + 1], li, idx + 1});\n}\nreturn out;",
        visibleCases: [
            { input: {"lists": [[1, 4, 5], [1, 3, 4], [2, 6]]}, output: [1, 1, 2, 3, 4, 4, 5, 6], explanation: "Merge three lists" },
            { input: {"lists": []}, output: [] },
        ],
        hiddenCases: [
            { input: {"lists": [[]]}, output: [] },
            { input: {"lists": [[1], [2, 3]]}, output: [1, 2, 3] },
            { input: {"lists": [[1, 2, 3]]}, output: [1, 2, 3] },
            { input: {"lists": [[1], [1]]}, output: [1, 1] },
            { input: {"lists": [[1, 2], [3, 4], [5, 6]]}, output: [1, 2, 3, 4, 5, 6] },
            { input: {"lists": [[1, 4, 5, 6], [2, 3]]}, output: [1, 2, 3, 4, 5, 6] },
            { input: {"lists": [[-1, 1], [0, 2]]}, output: [-1, 0, 1, 2] },
            { input: {"lists": [[1, 2, 3, 4, 5]]}, output: [1, 2, 3, 4, 5] },
        ],
    },
    {
        num: 85,
        slug: "largest-rectangle-in-histogram",
        title: "Largest Rectangle in Histogram",
        difficulty: "HARD",
        topics: ["stack", "arrays"],
        inputFormat: "{ heights: number[] }",
        outputFormat: "number",
        constraints: "1 <= heights.length <= 10^5; 0 <= heights[i] <= 10^4",
        hints: ["Maintain a monotonic increasing stack.", "Pop when height drops to compute width."],
        pythonBody: "def solve(data):\n    heights = data.get(\"heights\", [])\n    st = []\n    best = 0\n    heights = [0] + heights + [0]\n    for i, h in enumerate(heights):\n        while st and heights[st[-1]] > h:\n            H = heights[st.pop()]\n            W = i - st[-1] - 1\n            best = max(best, H * W)\n        st.append(i)\n    return best",
        javaBody: "JsonArray arr = data.has(\"heights\") ? data.getAsJsonArray(\"heights\") : new JsonArray();\nint[] h = new int[arr.size() + 2];\nh[0] = 0;\nfor (int i = 0; i < arr.size(); i++) h[i + 1] = arr.get(i).getAsInt();\nh[h.length - 1] = 0;\nDeque<Integer> st = new ArrayDeque<>();\nint best = 0;\nfor (int i = 0; i < h.length; i++) {\n    while (!st.isEmpty() && h[st.peek()] > h[i]) {\n        int H = h[st.pop()];\n        int W = i - st.peek() - 1;\n        best = Math.max(best, H * W);\n    }\n    st.push(i);\n}\nreturn best;",
        cppBody: "std::vector<int> heights = data.value(\"heights\", std::vector<int>{});\nheights.insert(heights.begin(), 0);\nheights.push_back(0);\nstd::vector<int> st;\nint best = 0;\nfor (int i = 0; i < static_cast<int>(heights.size()); i++) {\n    while (!st.empty() && heights[st.back()] > heights[i]) {\n        int H = heights[st.back()]; st.pop_back();\n        int W = i - st.back() - 1;\n        best = std::max(best, H * W);\n    }\n    st.push_back(i);\n}\nreturn best;",
        visibleCases: [
            { input: {"heights": [2, 1, 5, 6, 2, 3]}, output: 10, explanation: "Max area 10" },
            { input: {"heights": [2, 4]}, output: 4 },
        ],
        hiddenCases: [
            { input: {"heights": [1]}, output: 1 },
            { input: {"heights": [2, 2]}, output: 4 },
            { input: {"heights": [1, 1]}, output: 2 },
            { input: {"heights": [6, 2, 5, 4, 5, 6, 3]}, output: 16 },
            { input: {"heights": [1, 2, 3, 4, 5]}, output: 9 },
            { input: {"heights": [5, 4, 1, 2]}, output: 8 },
            { input: {"heights": [0, 9]}, output: 9 },
            { input: {"heights": [2, 1, 2]}, output: 3 },
        ],
    },
    {
        num: 86,
        slug: "word-ladder",
        title: "Word Ladder",
        difficulty: "HARD",
        topics: ["graphs", "queue", "strings"],
        inputFormat: "{ beginWord: string, endWord: string, wordList: string[] }",
        outputFormat: "number (path length, 0 if none)",
        constraints: "All words same length; 1 <= wordList.length <= 5000",
        hints: ["BFS over one-letter mutations.", "Remove visited words from the set."],
        pythonBody: "def solve(data):\n    from collections import deque\n    begin = data.get(\"beginWord\", \"\")\n    end = data.get(\"endWord\", \"\")\n    words = set(data.get(\"wordList\", []))\n    if end not in words:\n        return 0\n    q = deque([(begin, 1)])\n    while q:\n        w, d = q.popleft()\n        if w == end:\n            return d\n        for i in range(len(w)):\n            for c in \"abcdefghijklmnopqrstuvwxyz\":\n                nw = w[:i] + c + w[i + 1:]\n                if nw in words:\n                    words.remove(nw)\n                    q.append((nw, d + 1))\n    return 0",
        javaBody: "String begin = data.has(\"beginWord\") ? data.get(\"beginWord\").getAsString() : \"\";\nString end = data.has(\"endWord\") ? data.get(\"endWord\").getAsString() : \"\";\nSet<String> words = new HashSet<>();\nif (data.has(\"wordList\")) for (JsonElement e : data.getAsJsonArray(\"wordList\")) words.add(e.getAsString());\nif (!words.contains(end)) return 0;\nDeque<String[]> q = new ArrayDeque<>();\nq.offer(new String[]{begin, \"1\"});\nwhile (!q.isEmpty()) {\n    String[] cur = q.poll();\n    String w = cur[0];\n    int d = Integer.parseInt(cur[1]);\n    if (w.equals(end)) return d;\n    char[] arr = w.toCharArray();\n    for (int i = 0; i < arr.length; i++) {\n        char old = arr[i];\n        for (char c = 'a'; c <= 'z'; c++) {\n            arr[i] = c;\n            String nw = new String(arr);\n            if (words.remove(nw)) q.offer(new String[]{nw, String.valueOf(d + 1)});\n        }\n        arr[i] = old;\n    }\n}\nreturn 0;",
        cppBody: "std::string begin = data.value(\"beginWord\", \"\");\nstd::string end = data.value(\"endWord\", \"\");\nstd::unordered_set<std::string> words;\nfor (const auto& w : data.value(\"wordList\", std::vector<std::string>{})) words.insert(w);\nif (!words.count(end)) return 0;\nstd::queue<std::pair<std::string,int>> q;\nq.push({begin, 1});\nwhile (!q.empty()) {\n    auto [w, d] = q.front(); q.pop();\n    if (w == end) return d;\n    for (int i = 0; i < static_cast<int>(w.size()); i++) {\n        char old = w[i];\n        for (char c = 'a'; c <= 'z'; c++) {\n            std::string nw = w; nw[i] = c;\n            if (words.erase(nw)) q.push({nw, d + 1});\n        }\n        const_cast<std::string&>(w)[i] = old;\n    }\n}\nreturn 0;",
        visibleCases: [
            { input: {"beginWord": "hit", "endWord": "cog", "wordList": ["hot", "dot", "dog", "lot", "log", "cog"]}, output: 5, explanation: "Length 5" },
            { input: {"beginWord": "hit", "endWord": "cog", "wordList": ["hot", "dot", "dog", "lot", "log"]}, output: 0, explanation: "End not in list" },
        ],
        hiddenCases: [
            { input: {"beginWord": "a", "endWord": "c", "wordList": ["a", "b", "c"]}, output: 2 },
            { input: {"beginWord": "hot", "endWord": "dog", "wordList": ["hot", "dog"]}, output: 0 },
            { input: {"beginWord": "talk", "endWord": "walk", "wordList": ["talk", "walk"]}, output: 2 },
            { input: {"beginWord": "hit", "endWord": "cog", "wordList": ["hot", "cog", "dot", "dog"]}, output: 5 },
            { input: {"beginWord": "a", "endWord": "b", "wordList": ["a", "b", "c"]}, output: 2 },
            { input: {"beginWord": "red", "endWord": "tax", "wordList": ["ted", "tex", "red", "tax", "tad", "den", "rex", "pee"]}, output: 4 },
            { input: {"beginWord": "qa", "endWord": "sq", "wordList": ["si", "go", "se", "cm", "so", "ph", "mt", "db", "mb", "sb", "kr", "ln", "tm", "le", "av", "sm", "ar", "ci", "ca", "br", "ti", "ba", "to", "ra", "fa", "yo", "ow", "sn", "ya", "cr", "po", "fe", "ho", "ma", "re", "or", "rn", "au", "ur", "rh", "sr", "tc", "lt", "lo", "as", "fr", "nb", "yb", "if", "pb", "ge", "th", "pm", "rb", "sh", "co", "ca", "ta", "lb", "la", "qi", "pa", "ni", "ho", "ne", "ut", "me", "nd", "sa", "fe", "ho", "la", "ou", "et", "le", "mo", "fa", "ge", "er", "me", "sn", "pu", "pr", "ni", "te", "ca", "ut", "be", "mi", "ta", "la", "ni", "fo", "ho", "ge", "ne", "be", "me", "ut", "ho", "si", "ha", "as", "or", "fo", "ti", "in", "it", "st", "er", "ha", "nd", "on", "to", "nt", "ha", "ou", "ea", "le", "ou", "nd", "ha", "ng", "es", "ce", "on", "al", "ra", "ed", "nd", "co", "ra", "te", "of", "on", "ha", "ng", "co", "mp", "le", "te"]}, output: 0 },
            { input: {"beginWord": "leet", "endWord": "code", "wordList": ["lest", "leet", "lose", "code", "lode", "robe", "lost"]}, output: 6 },
        ],
    },
    {
        num: 87,
        slug: "edit-distance",
        title: "Edit Distance",
        difficulty: "HARD",
        topics: ["dynamic-programming", "strings"],
        inputFormat: "{ word1: string, word2: string }",
        outputFormat: "number",
        constraints: "0 <= word1.length, word2.length <= 500",
        hints: ["DP on prefixes of both strings.", "Match, insert, delete, or replace."],
        pythonBody: "def solve(data):\n    w1 = data.get(\"word1\", \"\")\n    w2 = data.get(\"word2\", \"\")\n    m, n = len(w1), len(w2)\n    dp = list(range(n + 1))\n    for i in range(1, m + 1):\n        prev = dp[0]\n        dp[0] = i\n        for j in range(1, n + 1):\n            tmp = dp[j]\n            if w1[i - 1] == w2[j - 1]:\n                dp[j] = prev\n            else:\n                dp[j] = 1 + min(prev, dp[j], dp[j - 1])\n            prev = tmp\n    return dp[n]",
        javaBody: "String w1 = data.has(\"word1\") ? data.get(\"word1\").getAsString() : \"\";\nString w2 = data.has(\"word2\") ? data.get(\"word2\").getAsString() : \"\";\nint m = w1.length(), n = w2.length();\nint[] dp = new int[n + 1];\nfor (int j = 0; j <= n; j++) dp[j] = j;\nfor (int i = 1; i <= m; i++) {\n    int prev = dp[0];\n    dp[0] = i;\n    for (int j = 1; j <= n; j++) {\n        int tmp = dp[j];\n        if (w1.charAt(i - 1) == w2.charAt(j - 1)) dp[j] = prev;\n        else dp[j] = 1 + Math.min(prev, Math.min(dp[j], dp[j - 1]));\n        prev = tmp;\n    }\n}\nreturn dp[n];",
        cppBody: "std::string w1 = data.value(\"word1\", \"\");\nstd::string w2 = data.value(\"word2\", \"\");\nint m = static_cast<int>(w1.size()), n = static_cast<int>(w2.size());\nstd::vector<int> dp(n + 1);\nstd::iota(dp.begin(), dp.end(), 0);\nfor (int i = 1; i <= m; i++) {\n    int prev = dp[0];\n    dp[0] = i;\n    for (int j = 1; j <= n; j++) {\n        int tmp = dp[j];\n        if (w1[i - 1] == w2[j - 1]) dp[j] = prev;\n        else dp[j] = 1 + std::min({prev, dp[j], dp[j - 1]});\n        prev = tmp;\n    }\n}\nreturn dp[n];",
        visibleCases: [
            { input: {"word1": "horse", "word2": "ros"}, output: 3, explanation: "3 operations" },
            { input: {"word1": "", "word2": ""}, output: 0 },
        ],
        hiddenCases: [
            { input: {"word1": "a", "word2": "b"}, output: 1 },
            { input: {"word1": "abc", "word2": "abc"}, output: 0 },
            { input: {"word1": "abc", "word2": "yabc"}, output: 1 },
            { input: {"word1": "intention", "word2": "execution"}, output: 5 },
            { input: {"word1": "a", "word2": ""}, output: 1 },
            { input: {"word1": "", "word2": "a"}, output: 1 },
            { input: {"word1": "park", "word2": "spake"}, output: 3 },
            { input: {"word1": "sea", "word2": "eat"}, output: 2 },
        ],
    },
    {
        num: 88,
        slug: "n-queens",
        title: "N-Queens",
        difficulty: "HARD",
        topics: ["backtracking"],
        inputFormat: "{ n: number }",
        outputFormat: "string[][] (board rows per solution)",
        constraints: "1 <= n <= 9",
        hints: ["Track columns and diagonals.", "Place queens row by row."],
        pythonBody: "def solve(data):\n    n = data.get(\"n\", 0)\n    res = []\n    cols, d1, d2 = set(), set(), set()\n    board = [\".\" * n for _ in range(n)]\n\n    def dfs(r):\n        if r == n:\n            res.append(board[:])\n            return\n        for c in range(n):\n            if c in cols or (r - c) in d1 or (r + c) in d2:\n                continue\n            cols.add(c); d1.add(r - c); d2.add(r + c)\n            row = list(board[r]); row[c] = \"Q\"; board[r] = \"\".join(row)\n            dfs(r + 1)\n            board[r] = \".\" * n\n            cols.remove(c); d1.remove(r - c); d2.remove(r + c)\n\n    dfs(0)\n    return res",
        javaBody: "int n = data.has(\"n\") ? data.get(\"n\").getAsInt() : 0;\nList<List<String>> res = new ArrayList<>();\nboolean[] cols = new boolean[n];\nboolean[] d1 = new boolean[2 * n];\nboolean[] d2 = new boolean[2 * n];\nchar[][] board = new char[n][n];\nfor (int i = 0; i < n; i++) Arrays.fill(board[i], '.');\nclass Dfs {\n    void go(int r) {\n        if (r == n) {\n            List<String> one = new ArrayList<>();\n            for (char[] row : board) one.add(new String(row));\n            res.add(one);\n            return;\n        }\n        for (int c = 0; c < n; c++) {\n            if (cols[c] || d1[r - c + n - 1] || d2[r + c]) continue;\n            cols[c] = d1[r - c + n - 1] = d2[r + c] = true;\n            board[r][c] = 'Q';\n            go(r + 1);\n            board[r][c] = '.';\n            cols[c] = d1[r - c + n - 1] = d2[r + c] = false;\n        }\n    }\n}\nnew Dfs().go(0);\nreturn res;",
        cppBody: "int n = data.value(\"n\", 0);\nstd::vector<std::vector<std::string>> res;\nstd::vector<bool> cols(n), d1(2 * n), d2(2 * n);\nstd::vector<std::string> board(n, std::string(n, '.'));\nstd::function<void(int)> dfs = [&](int r) {\n    if (r == n) { res.push_back(board); return; }\n    for (int c = 0; c < n; c++) {\n        if (cols[c] || d1[r - c + n - 1] || d2[r + c]) continue;\n        cols[c] = d1[r - c + n - 1] = d2[r + c] = true;\n        board[r][c] = 'Q';\n        dfs(r + 1);\n        board[r][c] = '.';\n        cols[c] = d1[r - c + n - 1] = d2[r + c] = false;\n    }\n};\ndfs(0);\nreturn res;",
        visibleCases: [
            { input: {"n": 4}, output: [[".Q..", "...Q", "Q...", "..Q."], ["..Q.", "Q...", "...Q", ".Q.."]], explanation: "Two solutions for n=4" },
            { input: {"n": 1}, output: [["Q"]] },
        ],
        hiddenCases: [
            { input: {"n": 2}, output: [] },
            { input: {"n": 3}, output: [] },
            { input: {"n": 5}, output: [["Q....", "..Q..", "....Q", ".Q...", "...Q."], ["Q....", "...Q.", ".Q...", "....Q", "..Q.."], [".Q...", "...Q.", "Q....", "..Q..", "....Q"], [".Q...", "....Q", "..Q..", "Q....", "...Q."], ["..Q..", "Q....", "...Q.", ".Q...", "....Q"], ["..Q..", "....Q", ".Q...", "...Q.", "Q...."], ["...Q.", "Q....", "..Q..", "....Q", ".Q..."], ["...Q.", ".Q...", "....Q", "..Q..", "Q...."], ["....Q", ".Q...", "...Q.", "Q....", "..Q.."], ["....Q", "..Q..", "Q....", "...Q.", ".Q..."]] },
            { input: {"n": 6}, output: [[".Q....", "...Q..", ".....Q", "Q.....", "..Q...", "....Q."], ["..Q...", ".....Q", ".Q....", "....Q.", "Q.....", "...Q.."], ["...Q..", "Q.....", "....Q.", ".Q....", ".....Q", "..Q..."], ["....Q.", "..Q...", "Q.....", ".....Q", "...Q..", ".Q...."]] },
            { input: {"n": 7}, output: [["Q......", "..Q....", "....Q..", "......Q", ".Q.....", "...Q...", ".....Q."], ["Q......", "...Q...", "......Q", "..Q....", ".....Q.", ".Q.....", "....Q.."], ["Q......", "....Q..", ".Q.....", ".....Q.", "..Q....", "......Q", "...Q..."], ["Q......", ".....Q.", "...Q...", ".Q.....", "......Q", "....Q..", "..Q...."], [".Q.....", "...Q...", "Q......", "......Q", "....Q..", "..Q....", ".....Q."], [".Q.....", "...Q...", ".....Q.", "Q......", "..Q....", "....Q..", "......Q"], [".Q.....", "....Q..", "Q......", "...Q...", "......Q", "..Q....", ".....Q."], [".Q.....", "....Q..", "..Q....", "Q......", "......Q", "...Q...", ".....Q."], [".Q.....", "....Q..", "......Q", "...Q...", "Q......", "..Q....", ".....Q."], [".Q.....", ".....Q.", "..Q....", "......Q", "...Q...", "Q......", "....Q.."], [".Q.....", "......Q", "....Q..", "..Q....", "Q......", ".....Q.", "...Q..."], ["..Q....", "Q......", ".....Q.", ".Q.....", "....Q..", "......Q", "...Q..."], ["..Q....", "Q......", ".....Q.", "...Q...", ".Q.....", "......Q", "....Q.."], ["..Q....", "....Q..", "......Q", ".Q.....", "...Q...", ".....Q.", "Q......"], ["..Q....", ".....Q.", ".Q.....", "....Q..", "Q......", "...Q...", "......Q"], ["..Q....", "......Q", ".Q.....", "...Q...", ".....Q.", "Q......", "....Q.."], ["..Q....", "......Q", "...Q...", "Q......", "....Q..", ".Q.....", ".....Q."], ["...Q...", "Q......", "..Q....", ".....Q.", ".Q.....", "......Q", "....Q.."], ["...Q...", "Q......", "....Q..", ".Q.....", ".....Q.", "..Q....", "......Q"], ["...Q...", ".Q.....", "......Q", "....Q..", "..Q....", "Q......", ".....Q."], ["...Q...", ".....Q.", "Q......", "..Q....", "....Q..", "......Q", ".Q....."], ["...Q...", "......Q", "..Q....", ".....Q.", ".Q.....", "....Q..", "Q......"], ["...Q...", "......Q", "....Q..", ".Q.....", ".....Q.", "Q......", "..Q...."], ["....Q..", "Q......", "...Q...", "......Q", "..Q....", ".....Q.", ".Q....."], ["....Q..", "Q......", ".....Q.", "...Q...", ".Q.....", "......Q", "..Q...."], ["....Q..", ".Q.....", ".....Q.", "..Q....", "......Q", "...Q...", "Q......"], ["....Q..", "..Q....", "Q......", ".....Q.", "...Q...", ".Q.....", "......Q"], ["....Q..", "......Q", ".Q.....", "...Q...", ".....Q.", "Q......", "..Q...."], ["....Q..", "......Q", ".Q.....", ".....Q.", "..Q....", "Q......", "...Q..."], [".....Q.", "Q......", "..Q....", "....Q..", "......Q", ".Q.....", "...Q..."], [".....Q.", ".Q.....", "....Q..", "Q......", "...Q...", "......Q", "..Q...."], [".....Q.", "..Q....", "Q......", "...Q...", "......Q", "....Q..", ".Q....."], [".....Q.", "..Q....", "....Q..", "......Q", "Q......", "...Q...", ".Q....."], [".....Q.", "..Q....", "......Q", "...Q...", "Q......", "....Q..", ".Q....."], [".....Q.", "...Q...", ".Q.....", "......Q", "....Q..", "..Q....", "Q......"], [".....Q.", "...Q...", "......Q", "Q......", "..Q....", "....Q..", ".Q....."], ["......Q", ".Q.....", "...Q...", ".....Q.", "Q......", "..Q....", "....Q.."], ["......Q", "..Q....", ".....Q.", ".Q.....", "....Q..", "Q......", "...Q..."], ["......Q", "...Q...", "Q......", "....Q..", ".Q.....", ".....Q.", "..Q...."], ["......Q", "....Q..", "..Q....", "Q......", ".....Q.", "...Q...", ".Q....."]] },
            { input: {"n": 8}, output: [["Q.......", "....Q...", ".......Q", ".....Q..", "..Q.....", "......Q.", ".Q......", "...Q...."], ["Q.......", ".....Q..", ".......Q", "..Q.....", "......Q.", "...Q....", ".Q......", "....Q..."], ["Q.......", "......Q.", "...Q....", ".....Q..", ".......Q", ".Q......", "....Q...", "..Q....."], ["Q.......", "......Q.", "....Q...", ".......Q", ".Q......", "...Q....", ".....Q..", "..Q....."], [".Q......", "...Q....", ".....Q..", ".......Q", "..Q.....", "Q.......", "......Q.", "....Q..."], [".Q......", "....Q...", "......Q.", "Q.......", "..Q.....", ".......Q", ".....Q..", "...Q...."], [".Q......", "....Q...", "......Q.", "...Q....", "Q.......", ".......Q", ".....Q..", "..Q....."], [".Q......", ".....Q..", "Q.......", "......Q.", "...Q....", ".......Q", "..Q.....", "....Q..."], [".Q......", ".....Q..", ".......Q", "..Q.....", "Q.......", "...Q....", "......Q.", "....Q..."], [".Q......", "......Q.", "..Q.....", ".....Q..", ".......Q", "....Q...", "Q.......", "...Q...."], [".Q......", "......Q.", "....Q...", ".......Q", "Q.......", "...Q....", ".....Q..", "..Q....."], [".Q......", ".......Q", ".....Q..", "Q.......", "..Q.....", "....Q...", "......Q.", "...Q...."], ["..Q.....", "Q.......", "......Q.", "....Q...", ".......Q", ".Q......", "...Q....", ".....Q.."], ["..Q.....", "....Q...", ".Q......", ".......Q", "Q.......", "......Q.", "...Q....", ".....Q.."], ["..Q.....", "....Q...", ".Q......", ".......Q", ".....Q..", "...Q....", "......Q.", "Q......."], ["..Q.....", "....Q...", "......Q.", "Q.......", "...Q....", ".Q......", ".......Q", ".....Q.."], ["..Q.....", "....Q...", ".......Q", "...Q....", "Q.......", "......Q.", ".Q......", ".....Q.."], ["..Q.....", ".....Q..", ".Q......", "....Q...", ".......Q", "Q.......", "......Q.", "...Q...."], ["..Q.....", ".....Q..", ".Q......", "......Q.", "Q.......", "...Q....", ".......Q", "....Q..."], ["..Q.....", ".....Q..", ".Q......", "......Q.", "....Q...", "Q.......", ".......Q", "...Q...."], ["..Q.....", ".....Q..", "...Q....", "Q.......", ".......Q", "....Q...", "......Q.", ".Q......"], ["..Q.....", ".....Q..", "...Q....", ".Q......", ".......Q", "....Q...", "......Q.", "Q......."], ["..Q.....", ".....Q..", ".......Q", "Q.......", "...Q....", "......Q.", "....Q...", ".Q......"], ["..Q.....", ".....Q..", ".......Q", "Q.......", "....Q...", "......Q.", ".Q......", "...Q...."], ["..Q.....", ".....Q..", ".......Q", ".Q......", "...Q....", "Q.......", "......Q.", "....Q..."], ["..Q.....", "......Q.", ".Q......", ".......Q", "....Q...", "Q.......", "...Q....", ".....Q.."], ["..Q.....", "......Q.", ".Q......", ".......Q", ".....Q..", "...Q....", "Q.......", "....Q..."], ["..Q.....", ".......Q", "...Q....", "......Q.", "Q.......", ".....Q..", ".Q......", "....Q..."], ["...Q....", "Q.......", "....Q...", ".......Q", ".Q......", "......Q.", "..Q.....", ".....Q.."], ["...Q....", "Q.......", "....Q...", ".......Q", ".....Q..", "..Q.....", "......Q.", ".Q......"], ["...Q....", ".Q......", "....Q...", ".......Q", ".....Q..", "Q.......", "..Q.....", "......Q."], ["...Q....", ".Q......", "......Q.", "..Q.....", ".....Q..", ".......Q", "Q.......", "....Q..."], ["...Q....", ".Q......", "......Q.", "..Q.....", ".....Q..", ".......Q", "....Q...", "Q......."], ["...Q....", ".Q......", "......Q.", "....Q...", "Q.......", ".......Q", ".....Q..", "..Q....."], ["...Q....", ".Q......", ".......Q", "....Q...", "......Q.", "Q.......", "..Q.....", ".....Q.."], ["...Q....", ".Q......", ".......Q", ".....Q..", "Q.......", "..Q.....", "....Q...", "......Q."], ["...Q....", ".....Q..", "Q.......", "....Q...", ".Q......", ".......Q", "..Q.....", "......Q."], ["...Q....", ".....Q..", ".......Q", ".Q......", "......Q.", "Q.......", "..Q.....", "....Q..."], ["...Q....", ".....Q..", ".......Q", "..Q.....", "Q.......", "......Q.", "....Q...", ".Q......"], ["...Q....", "......Q.", "Q.......", ".......Q", "....Q...", ".Q......", ".....Q..", "..Q....."], ["...Q....", "......Q.", "..Q.....", ".......Q", ".Q......", "....Q...", "Q.......", ".....Q.."], ["...Q....", "......Q.", "....Q...", ".Q......", ".....Q..", "Q.......", "..Q.....", ".......Q"], ["...Q....", "......Q.", "....Q...", "..Q.....", "Q.......", ".....Q..", ".......Q", ".Q......"], ["...Q....", ".......Q", "Q.......", "..Q.....", ".....Q..", ".Q......", "......Q.", "....Q..."], ["...Q....", ".......Q", "Q.......", "....Q...", "......Q.", ".Q......", ".....Q..", "..Q....."], ["...Q....", ".......Q", "....Q...", "..Q.....", "Q.......", "......Q.", ".Q......", ".....Q.."], ["....Q...", "Q.......", "...Q....", ".....Q..", ".......Q", ".Q......", "......Q.", "..Q....."], ["....Q...", "Q.......", ".......Q", "...Q....", ".Q......", "......Q.", "..Q.....", ".....Q.."], ["....Q...", "Q.......", ".......Q", ".....Q..", "..Q.....", "......Q.", ".Q......", "...Q...."], ["....Q...", ".Q......", "...Q....", ".....Q..", ".......Q", "..Q.....", "Q.......", "......Q."], ["....Q...", ".Q......", "...Q....", "......Q.", "..Q.....", ".......Q", ".....Q..", "Q......."], ["....Q...", ".Q......", ".....Q..", "Q.......", "......Q.", "...Q....", ".......Q", "..Q....."], ["....Q...", ".Q......", ".......Q", "Q.......", "...Q....", "......Q.", "..Q.....", ".....Q.."], ["....Q...", "..Q.....", "Q.......", ".....Q..", ".......Q", ".Q......", "...Q....", "......Q."], ["....Q...", "..Q.....", "Q.......", "......Q.", ".Q......", ".......Q", ".....Q..", "...Q...."], ["....Q...", "..Q.....", ".......Q", "...Q....", "......Q.", "Q.......", ".....Q..", ".Q......"], ["....Q...", "......Q.", "Q.......", "..Q.....", ".......Q", ".....Q..", "...Q....", ".Q......"], ["....Q...", "......Q.", "Q.......", "...Q....", ".Q......", ".......Q", ".....Q..", "..Q....."], ["....Q...", "......Q.", ".Q......", "...Q....", ".......Q", "Q.......", "..Q.....", ".....Q.."], ["....Q...", "......Q.", ".Q......", ".....Q..", "..Q.....", "Q.......", "...Q....", ".......Q"], ["....Q...", "......Q.", ".Q......", ".....Q..", "..Q.....", "Q.......", ".......Q", "...Q...."], ["....Q...", "......Q.", "...Q....", "Q.......", "..Q.....", ".......Q", ".....Q..", ".Q......"], ["....Q...", ".......Q", "...Q....", "Q.......", "..Q.....", ".....Q..", ".Q......", "......Q."], ["....Q...", ".......Q", "...Q....", "Q.......", "......Q.", ".Q......", ".....Q..", "..Q....."], [".....Q..", "Q.......", "....Q...", ".Q......", ".......Q", "..Q.....", "......Q.", "...Q...."], [".....Q..", ".Q......", "......Q.", "Q.......", "..Q.....", "....Q...", ".......Q", "...Q...."], [".....Q..", ".Q......", "......Q.", "Q.......", "...Q....", ".......Q", "....Q...", "..Q....."], [".....Q..", "..Q.....", "Q.......", "......Q.", "....Q...", ".......Q", ".Q......", "...Q...."], [".....Q..", "..Q.....", "Q.......", ".......Q", "...Q....", ".Q......", "......Q.", "....Q..."], [".....Q..", "..Q.....", "Q.......", ".......Q", "....Q...", ".Q......", "...Q....", "......Q."], [".....Q..", "..Q.....", "....Q...", "......Q.", "Q.......", "...Q....", ".Q......", ".......Q"], [".....Q..", "..Q.....", "....Q...", ".......Q", "Q.......", "...Q....", ".Q......", "......Q."], [".....Q..", "..Q.....", "......Q.", ".Q......", "...Q....", ".......Q", "Q.......", "....Q..."], [".....Q..", "..Q.....", "......Q.", ".Q......", ".......Q", "....Q...", "Q.......", "...Q...."], [".....Q..", "..Q.....", "......Q.", "...Q....", "Q.......", ".......Q", ".Q......", "....Q..."], [".....Q..", "...Q....", "Q.......", "....Q...", ".......Q", ".Q......", "......Q.", "..Q....."], [".....Q..", "...Q....", ".Q......", ".......Q", "....Q...", "......Q.", "Q.......", "..Q....."], [".....Q..", "...Q....", "......Q.", "Q.......", "..Q.....", "....Q...", ".Q......", ".......Q"], [".....Q..", "...Q....", "......Q.", "Q.......", ".......Q", ".Q......", "....Q...", "..Q....."], [".....Q..", ".......Q", ".Q......", "...Q....", "Q.......", "......Q.", "....Q...", "..Q....."], ["......Q.", "Q.......", "..Q.....", ".......Q", ".....Q..", "...Q....", ".Q......", "....Q..."], ["......Q.", ".Q......", "...Q....", "Q.......", ".......Q", "....Q...", "..Q.....", ".....Q.."], ["......Q.", ".Q......", ".....Q..", "..Q.....", "Q.......", "...Q....", ".......Q", "....Q..."], ["......Q.", "..Q.....", "Q.......", ".....Q..", ".......Q", "....Q...", ".Q......", "...Q...."], ["......Q.", "..Q.....", ".......Q", ".Q......", "....Q...", "Q.......", ".....Q..", "...Q...."], ["......Q.", "...Q....", ".Q......", "....Q...", ".......Q", "Q.......", "..Q.....", ".....Q.."], ["......Q.", "...Q....", ".Q......", ".......Q", ".....Q..", "Q.......", "..Q.....", "....Q..."], ["......Q.", "....Q...", "..Q.....", "Q.......", ".....Q..", ".......Q", ".Q......", "...Q...."], [".......Q", ".Q......", "...Q....", "Q.......", "......Q.", "....Q...", "..Q.....", ".....Q.."], [".......Q", ".Q......", "....Q...", "..Q.....", "Q.......", "......Q.", "...Q....", ".....Q.."], [".......Q", "..Q.....", "Q.......", ".....Q..", ".Q......", "....Q...", "......Q.", "...Q...."], [".......Q", "...Q....", "Q.......", "..Q.....", ".....Q..", ".Q......", "......Q.", "....Q..."]] },
            { input: {"n": 1}, output: [["Q"]] },
            { input: {"n": 5}, output: [["Q....", "..Q..", "....Q", ".Q...", "...Q."], ["Q....", "...Q.", ".Q...", "....Q", "..Q.."], [".Q...", "...Q.", "Q....", "..Q..", "....Q"], [".Q...", "....Q", "..Q..", "Q....", "...Q."], ["..Q..", "Q....", "...Q.", ".Q...", "....Q"], ["..Q..", "....Q", ".Q...", "...Q.", "Q...."], ["...Q.", "Q....", "..Q..", "....Q", ".Q..."], ["...Q.", ".Q...", "....Q", "..Q..", "Q...."], ["....Q", ".Q...", "...Q.", "Q....", "..Q.."], ["....Q", "..Q..", "Q....", "...Q.", ".Q..."]] },
        ],
    },
    {
        num: 89,
        slug: "regular-expression-matching",
        title: "Regular Expression Matching",
        difficulty: "HARD",
        topics: ["dynamic-programming", "strings"],
        inputFormat: "{ s: string, p: string }",
        outputFormat: "boolean",
        constraints: "1 <= s.length <= 20; 1 <= p.length <= 30",
        hints: ["DP over prefixes of s and p.", "Handle '*' by zero or more of prior char."],
        pythonBody: "def solve(data):\n    s = data.get(\"s\", \"\")\n    p = data.get(\"p\", \"\")\n    m, n = len(s), len(p)\n    dp = [[False] * (n + 1) for _ in range(m + 1)]\n    dp[0][0] = True\n    for j in range(2, n + 1):\n        if p[j - 1] == \"*\":\n            dp[0][j] = dp[0][j - 2]\n    for i in range(1, m + 1):\n        for j in range(1, n + 1):\n            if p[j - 1] == \"*\":\n                dp[i][j] = dp[i][j - 2]\n                if p[j - 2] == \".\" or p[j - 2] == s[i - 1]:\n                    dp[i][j] = dp[i][j] or dp[i - 1][j]\n            elif p[j - 1] == \".\" or p[j - 1] == s[i - 1]:\n                dp[i][j] = dp[i - 1][j - 1]\n    return dp[m][n]",
        javaBody: "String s = data.has(\"s\") ? data.get(\"s\").getAsString() : \"\";\nString p = data.has(\"p\") ? data.get(\"p\").getAsString() : \"\";\nint m = s.length(), n = p.length();\nboolean[][] dp = new boolean[m + 1][n + 1];\ndp[0][0] = true;\nfor (int j = 2; j <= n; j++) if (p.charAt(j - 1) == '*') dp[0][j] = dp[0][j - 2];\nfor (int i = 1; i <= m; i++) {\n    for (int j = 1; j <= n; j++) {\n        if (p.charAt(j - 1) == '*') {\n            dp[i][j] = dp[i][j - 2];\n            if (p.charAt(j - 2) == '.' || p.charAt(j - 2) == s.charAt(i - 1)) dp[i][j] = dp[i][j] || dp[i - 1][j];\n        } else if (p.charAt(j - 1) == '.' || p.charAt(j - 1) == s.charAt(i - 1)) {\n            dp[i][j] = dp[i - 1][j - 1];\n        }\n    }\n}\nreturn dp[m][n];",
        cppBody: "std::string s = data.value(\"s\", \"\");\nstd::string p = data.value(\"p\", \"\");\nint m = static_cast<int>(s.size()), n = static_cast<int>(p.size());\nstd::vector<std::vector<bool>> dp(m + 1, std::vector<bool>(n + 1));\ndp[0][0] = true;\nfor (int j = 2; j <= n; j++) if (p[j - 1] == '*') dp[0][j] = dp[0][j - 2];\nfor (int i = 1; i <= m; i++) {\n    for (int j = 1; j <= n; j++) {\n        if (p[j - 1] == '*') {\n            dp[i][j] = dp[i][j - 2];\n            if (p[j - 2] == '.' || p[j - 2] == s[i - 1]) dp[i][j] = dp[i][j] || dp[i - 1][j];\n        } else if (p[j - 1] == '.' || p[j - 1] == s[i - 1]) {\n            dp[i][j] = dp[i - 1][j - 1];\n        }\n    }\n}\nreturn dp[m][n];",
        visibleCases: [
            { input: {"s": "aa", "p": "a*"}, output: true, explanation: "a* matches aa" },
            { input: {"s": "ab", "p": ".*"}, output: true },
        ],
        hiddenCases: [
            { input: {"s": "aab", "p": "c*a*b"}, output: true },
            { input: {"s": "mississippi", "p": "mis*is*p*."}, output: false },
            { input: {"s": "a", "p": "ab*"}, output: true },
            { input: {"s": "a", "p": "ab*a"}, output: false },
            { input: {"s": "aaa", "p": "a*a"}, output: true },
            { input: {"s": "ab", "p": ".*c"}, output: false },
            { input: {"s": "aaa", "p": "aaaa"}, output: false },
            { input: {"s": "", "p": ".*"}, output: true },
        ],
    },
    {
        num: 90,
        slug: "serialize-and-deserialize-binary-tree",
        title: "Serialize and Deserialize Binary Tree",
        difficulty: "HARD",
        topics: ["trees", "queue"],
        inputFormat: "{ root: (number | null)[] }",
        outputFormat: "string (level-order JSON)",
        constraints: "Tree has up to 10^4 nodes; values in [-1000, 1000]",
        hints: ["BFS level-order with null markers.", "Trim trailing nulls in output."],
        pythonBody: "def solve(data):\n    from collections import deque\n    arr = data.get(\"root\", [])\n    if not arr:\n        return \"[]\"\n    nodes = [None if v is None else {\"val\": v, \"left\": None, \"right\": None} for v in arr]\n    kids = nodes[::-1]\n    root = kids.pop()\n    for i, node in enumerate(nodes):\n        if node is None:\n            continue\n        if i * 2 + 1 < len(nodes):\n            node[\"left\"] = nodes[i * 2 + 1]\n        if i * 2 + 2 < len(nodes):\n            node[\"right\"] = nodes[i * 2 + 2]\n    q = deque([root])\n    out = []\n    while q:\n        node = q.popleft()\n        if node is None:\n            out.append(None)\n            continue\n        out.append(node[\"val\"])\n        q.append(node.get(\"left\"))\n        q.append(node.get(\"right\"))\n    while out and out[-1] is None:\n        out.pop()\n    import json\n    return json.dumps(out)",
        javaBody: "JsonArray arr = data.has(\"root\") ? data.getAsJsonArray(\"root\") : new JsonArray();\nif (arr.size() == 0) return \"[]\";\nclass Node { Integer val; Node left, right; Node(Integer v){val=v;} }\nList<Node> nodes = new ArrayList<>();\nfor (JsonElement e : arr) nodes.add(e.isJsonNull() ? null : new Node(e.getAsInt()));\nList<Node> kids = new ArrayList<>(nodes);\nCollections.reverse(kids);\nNode root = kids.remove(kids.size() - 1);\nfor (int i = 0; i < nodes.size(); i++) {\n    if (nodes.get(i) == null) continue;\n    if (i * 2 + 1 < nodes.size()) nodes.get(i).left = nodes.get(i * 2 + 1);\n    if (i * 2 + 2 < nodes.size()) nodes.get(i).right = nodes.get(i * 2 + 2);\n}\nDeque<Node> q = new ArrayDeque<>();\nq.offer(root);\nList<Integer> out = new ArrayList<>();\nwhile (!q.isEmpty()) {\n    Node node = q.poll();\n    if (node == null) { out.add(null); continue; }\n    out.add(node.val);\n    q.offer(node.left);\n    q.offer(node.right);\n}\nwhile (!out.isEmpty() && out.get(out.size() - 1) == null) out.remove(out.size() - 1);\nreturn new Gson().toJson(out);",
        cppBody: "std::vector<json> arr = data.value(\"root\", std::vector<json>{});\nif (arr.empty()) return json(\"[]\");\nstruct Node { int val; Node* left = nullptr; Node* right = nullptr; Node(int v): val(v) {} };\nstd::vector<Node*> nodes(arr.size(), nullptr);\nfor (size_t i = 0; i < arr.size(); i++) if (!arr[i].is_null()) nodes[i] = new Node(arr[i].get<int>());\nfor (size_t i = 0; i < nodes.size(); i++) {\n    if (!nodes[i]) continue;\n    if (i * 2 + 1 < nodes.size()) nodes[i]->left = nodes[i * 2 + 1];\n    if (i * 2 + 2 < nodes.size()) nodes[i]->right = nodes[i * 2 + 2];\n}\nstd::queue<Node*> q;\nq.push(nodes[0]);\njson out = json::array();\nwhile (!q.empty()) {\n    Node* node = q.front(); q.pop();\n    if (!node) { out.push_back(nullptr); continue; }\n    out.push_back(node->val);\n    q.push(node->left);\n    q.push(node->right);\n}\nwhile (!out.empty() && out.back().is_null()) out.erase(out.size() - 1);\nreturn out.dump();",
        visibleCases: [
            { input: {"root": [1, 2, 3, null, null, 4, 5]}, output: "[1, 2, 3, null, null, 4, 5]", explanation: "Level-order string" },
            { input: {"root": []}, output: "[]" },
        ],
        hiddenCases: [
            { input: {"root": [1]}, output: "[1]" },
            { input: {"root": [1, null, 2]}, output: "[1, null, 2]" },
            { input: {"root": [5, 4, 3, null, null, 2, 1]}, output: "[5, 4, 3, null, null, 2, 1]" },
            { input: {"root": [1, 2]}, output: "[1, 2]" },
            { input: {"root": [1, 2, null, 3]}, output: "[1, 2, null, 3]" },
            { input: {"root": [1, 2, 3, 4, 5, 6, 7]}, output: "[1, 2, 3, 4, 5, 6, 7]" },
            { input: {"root": [1, null, 2, null, 3]}, output: "[1, null, 2]" },
            { input: {"root": [10, 5, 15]}, output: "[10, 5, 15]" },
        ],
    },
    {
        num: 91,
        slug: "maximal-rectangle",
        title: "Maximal Rectangle",
        difficulty: "HARD",
        topics: ["stack", "dynamic-programming"],
        inputFormat: "{ matrix: string[][] }",
        outputFormat: "number",
        constraints: "1 <= rows, cols <= 200; matrix[i][j] is '0' or '1'",
        hints: ["Build histogram heights per row.", "Run largest-rectangle on each row."],
        pythonBody: "def solve(data):\n    matrix = data.get(\"matrix\", [])\n    if not matrix:\n        return 0\n    cols = len(matrix[0])\n    heights = [0] * cols\n    best = 0\n    def largest(h):\n        st = []\n        ans = 0\n        h = [0] + h + [0]\n        for i, x in enumerate(h):\n            while st and h[st[-1]] > x:\n                H = h[st.pop()]\n                W = i - st[-1] - 1\n                ans = max(ans, H * W)\n            st.append(i)\n        return ans\n    for row in matrix:\n        for j in range(cols):\n            heights[j] = heights[j] + 1 if row[j] == \"1\" else 0\n        best = max(best, largest(heights))\n    return best",
        javaBody: "JsonArray matrix = data.has(\"matrix\") ? data.getAsJsonArray(\"matrix\") : new JsonArray();\nif (matrix.size() == 0) return 0;\nint cols = matrix.get(0).getAsJsonArray().size();\nint[] heights = new int[cols];\nint best = 0;\nfor (JsonElement rowEl : matrix) {\n    JsonArray row = rowEl.getAsJsonArray();\n    for (int j = 0; j < cols; j++) heights[j] = \"1\".equals(row.get(j).getAsString()) ? heights[j] + 1 : 0;\n    int[] h = new int[heights.length + 2];\n    System.arraycopy(heights, 0, h, 1, heights.length);\n    Deque<Integer> st = new ArrayDeque<>();\n    for (int i = 0; i < h.length; i++) {\n        while (!st.isEmpty() && h[st.peek()] > h[i]) {\n            int H = h[st.pop()];\n            best = Math.max(best, H * (i - st.peek() - 1));\n        }\n        st.push(i);\n    }\n}\nreturn best;",
        cppBody: "std::vector<std::vector<std::string>> matrix = data.value(\"matrix\", std::vector<std::vector<std::string>>{});\nif (matrix.empty()) return 0;\nint cols = static_cast<int>(matrix[0].size());\nstd::vector<int> heights(cols);\nint best = 0;\nfor (const auto& row : matrix) {\n    for (int j = 0; j < cols; j++) heights[j] = row[j] == \"1\" ? heights[j] + 1 : 0;\n    std::vector<int> h = heights;\n    h.insert(h.begin(), 0); h.push_back(0);\n    std::vector<int> st;\n    for (int i = 0; i < static_cast<int>(h.size()); i++) {\n        while (!st.empty() && h[st.back()] > h[i]) {\n            int H = h[st.back()]; st.pop_back();\n            best = std::max(best, H * (i - st.back() - 1));\n        }\n        st.push_back(i);\n    }\n}\nreturn best;",
        visibleCases: [
            { input: {"matrix": [["1", "0", "1", "0", "0"], ["1", "0", "1", "1", "1"], ["1", "1", "1", "1", "1"], ["1", "0", "0", "1", "0"]]}, output: 6, explanation: "Area 6" },
            { input: {"matrix": [["0"]]}, output: 0 },
        ],
        hiddenCases: [
            { input: {"matrix": [["1", "1"]]}, output: 2 },
            { input: {"matrix": [["1", "1"], ["1", "1"]]}, output: 4 },
            { input: {"matrix": [["0", "1"], ["1", "0"]]}, output: 1 },
            { input: {"matrix": [["1", "0", "1"], ["1", "1", "1"]]}, output: 3 },
            { input: {"matrix": [["1", "0"], ["0", "1"], ["1", "0"]]}, output: 1 },
            { input: {"matrix": [["1", "1", "1", "1"]]}, output: 4 },
            { input: {"matrix": [["1", "0", "0"], ["1", "1", "1"], ["1", "1", "1"]]}, output: 6 },
            { input: {"matrix": [["0", "0"], ["0", "0"]]}, output: 0 },
        ],
    },
    {
        num: 92,
        slug: "sliding-window-maximum",
        title: "Sliding Window Maximum",
        difficulty: "HARD",
        topics: ["queue", "heap", "sliding-window"],
        inputFormat: "{ nums: number[], k: number }",
        outputFormat: "number[]",
        constraints: "1 <= nums.length <= 10^5; 1 <= k <= nums.length",
        hints: ["Deque stores indices in decreasing value order.", "Drop indices outside the window."],
        pythonBody: "def solve(data):\n    from collections import deque\n    nums = data.get(\"nums\", [])\n    k = data.get(\"k\", 1)\n    dq = deque()\n    out = []\n    for i, x in enumerate(nums):\n        while dq and nums[dq[-1]] <= x:\n            dq.pop()\n        dq.append(i)\n        if dq[0] <= i - k:\n            dq.popleft()\n        if i >= k - 1:\n            out.append(nums[dq[0]])\n    return out",
        javaBody: "JsonArray numsArr = data.has(\"nums\") ? data.getAsJsonArray(\"nums\") : new JsonArray();\nint k = data.has(\"k\") ? data.get(\"k\").getAsInt() : 1;\nint[] nums = new int[numsArr.size()];\nfor (int i = 0; i < nums.length; i++) nums[i] = numsArr.get(i).getAsInt();\nDeque<Integer> dq = new ArrayDeque<>();\nList<Integer> out = new ArrayList<>();\nfor (int i = 0; i < nums.length; i++) {\n    while (!dq.isEmpty() && nums[dq.peekLast()] <= nums[i]) dq.pollLast();\n    dq.offerLast(i);\n    if (dq.peekFirst() <= i - k) dq.pollFirst();\n    if (i >= k - 1) out.add(nums[dq.peekFirst()]);\n}\nreturn out;",
        cppBody: "std::vector<int> nums = data.value(\"nums\", std::vector<int>{});\nint k = data.value(\"k\", 1);\nstd::deque<int> dq;\nstd::vector<int> out;\nfor (int i = 0; i < static_cast<int>(nums.size()); i++) {\n    while (!dq.empty() && nums[dq.back()] <= nums[i]) dq.pop_back();\n    dq.push_back(i);\n    if (dq.front() <= i - k) dq.pop_front();\n    if (i >= k - 1) out.push_back(nums[dq.front()]);\n}\nreturn out;",
        visibleCases: [
            { input: {"nums": [1, 3, -1, -3, 5, 3, 6, 7], "k": 3}, output: [3, 3, 5, 5, 6, 7], explanation: "Window maxima" },
            { input: {"nums": [1], "k": 1}, output: [1] },
        ],
        hiddenCases: [
            { input: {"nums": [1, -1], "k": 1}, output: [1, -1] },
            { input: {"nums": [9, 11], "k": 2}, output: [11] },
            { input: {"nums": [4, 2, 12], "k": 2}, output: [4, 12] },
            { input: {"nums": [7, 2, 4], "k": 2}, output: [7, 4] },
            { input: {"nums": [1, 2, 3, 4, 5], "k": 2}, output: [2, 3, 4, 5] },
            { input: {"nums": [1, 3, 1, 2, 5], "k": 3}, output: [3, 3, 5] },
            { input: {"nums": [9, 10, 9, 8, 7], "k": 3}, output: [10, 10, 9] },
            { input: {"nums": [1, 2, 1, 0, 4, 2, 6], "k": 3}, output: [2, 2, 4, 4, 6] },
        ],
    },
    {
        num: 93,
        slug: "substring-with-concatenation-of-all-words",
        title: "Substring with Concatenation of All Words",
        difficulty: "HARD",
        topics: ["sliding-window", "hash-table"],
        inputFormat: "{ s: string, words: string[] }",
        outputFormat: "number[] (start indices)",
        constraints: "Words have equal length; 1 <= words.length <= 1000",
        hints: ["Slide by word length offsets.", "Count word frequencies in the window."],
        pythonBody: "def solve(data):\n    from collections import Counter\n    s = data.get(\"s\", \"\")\n    words = data.get(\"words\", [])\n    if not words:\n        return []\n    wlen = len(words[0])\n    n = len(words)\n    need = Counter(words)\n    res = []\n    for start in range(wlen):\n        left = start\n        seen = Counter()\n        used = 0\n        for right in range(start, len(s) - wlen + 1, wlen):\n            word = s[right:right + wlen]\n            if word not in need:\n                seen.clear(); used = 0; left = right + wlen; continue\n            seen[word] += 1; used += 1\n            while seen[word] > need[word]:\n                seen[s[left:left + wlen]] -= 1; used -= 1; left += wlen\n            if used == n:\n                res.append(left)\n    return sorted(res)",
        javaBody: "String s = data.has(\"s\") ? data.get(\"s\").getAsString() : \"\";\nList<String> words = new ArrayList<>();\nif (data.has(\"words\")) for (JsonElement e : data.getAsJsonArray(\"words\")) words.add(e.getAsString());\nif (words.isEmpty()) return new ArrayList<Integer>();\nint wlen = words.get(0).length(), n = words.size();\nMap<String, Integer> need = new HashMap<>();\nfor (String w : words) need.put(w, need.getOrDefault(w, 0) + 1);\nList<Integer> res = new ArrayList<>();\nfor (int start = 0; start < wlen; start++) {\n    int left = start, used = 0;\n    Map<String, Integer> seen = new HashMap<>();\n    for (int right = start; right <= s.length() - wlen; right += wlen) {\n        String word = s.substring(right, right + wlen);\n        if (!need.containsKey(word)) { seen.clear(); used = 0; left = right + wlen; continue; }\n        seen.put(word, seen.getOrDefault(word, 0) + 1); used++;\n        while (seen.get(word) > need.get(word)) {\n            String lw = s.substring(left, left + wlen);\n            seen.put(lw, seen.get(lw) - 1); used--; left += wlen;\n        }\n        if (used == n) res.add(left);\n    }\n}\nCollections.sort(res);\nreturn res;",
        cppBody: "std::string s = data.value(\"s\", \"\");\nstd::vector<std::string> words = data.value(\"words\", std::vector<std::string>{});\nif (words.empty()) return json::array();\nint wlen = static_cast<int>(words[0].size()), n = static_cast<int>(words.size());\nstd::unordered_map<std::string, int> need;\nfor (const auto& w : words) need[w]++;\nstd::vector<int> res;\nfor (int start = 0; start < wlen; start++) {\n    int left = start, used = 0;\n    std::unordered_map<std::string, int> seen;\n    for (int right = start; right + wlen <= static_cast<int>(s.size()); right += wlen) {\n        std::string word = s.substr(right, wlen);\n        if (!need.count(word)) { seen.clear(); used = 0; left = right + wlen; continue; }\n        seen[word]++; used++;\n        while (seen[word] > need[word]) {\n            std::string lw = s.substr(left, wlen);\n            if (--seen[lw] == 0) seen.erase(lw);\n            used--; left += wlen;\n        }\n        if (used == n) res.push_back(left);\n    }\n}\nstd::sort(res.begin(), res.end());\nreturn res;",
        visibleCases: [
            { input: {"s": "barfoothefoobarman", "words": ["foo", "bar"]}, output: [0, 9], explanation: "Indices 0 and 9" },
            { input: {"s": "wordgoodgoodgoodbestword", "words": ["word", "good", "best", "word"]}, output: [] },
        ],
        hiddenCases: [
            { input: {"s": "abababab", "words": ["ab", "ba"]}, output: [] },
            { input: {"s": "lingmindraboofooowingdingbarrwingmonkeypoundcake", "words": ["fooo", "barr", "wing", "ding", "wing"]}, output: [13] },
            { input: {"s": "aaa", "words": ["a", "a"]}, output: [0, 1] },
            { input: {"s": "abababab", "words": ["ab", "ab"]}, output: [0, 2, 4] },
            { input: {"s": "barfoofoobarthefoobarman", "words": ["bar", "foo", "the"]}, output: [6, 9, 12] },
            { input: {"s": "a", "words": ["a"]}, output: [0] },
            { input: {"s": "abab", "words": ["ab", "ab"]}, output: [0] },
            { input: {"s": "foobarthefoobarman", "words": ["bar", "foo", "the"]}, output: [0, 3, 6] },
        ],
    },
    {
        num: 94,
        slug: "binary-tree-maximum-path-sum",
        title: "Binary Tree Maximum Path Sum",
        difficulty: "HARD",
        topics: ["trees", "dynamic-programming"],
        inputFormat: "{ root: (number | null)[] }",
        outputFormat: "number",
        constraints: "Tree has up to 10^4 nodes; node values in [-1000, 1000]",
        hints: ["DFS returns best downward gain from a node.", "Update global max with left+node+right."],
        pythonBody: "def solve(data):\n    arr = data.get(\"root\", [])\n    if not arr:\n        return 0\n    nodes = [None if v is None else {\"val\": v, \"left\": None, \"right\": None} for v in arr]\n    kids = nodes[::-1]\n    root = kids.pop()\n    for i, node in enumerate(nodes):\n        if node is None:\n            continue\n        if i * 2 + 1 < len(nodes):\n            node[\"left\"] = nodes[i * 2 + 1]\n        if i * 2 + 2 < len(nodes):\n            node[\"right\"] = nodes[i * 2 + 2]\n    best = float(\"-inf\")\n    def gain(node):\n        nonlocal best\n        if not node:\n            return 0\n        l = max(0, gain(node[\"left\"]))\n        r = max(0, gain(node[\"right\"]))\n        best = max(best, node[\"val\"] + l + r)\n        return node[\"val\"] + max(l, r)\n    gain(root)\n    return best",
        javaBody: "JsonArray arr = data.has(\"root\") ? data.getAsJsonArray(\"root\") : new JsonArray();\nclass Node { int val; Node left, right; Node(int v){val=v;} }\nList<Node> nodes = new ArrayList<>();\nfor (JsonElement e : arr) nodes.add(e.isJsonNull() ? null : new Node(e.getAsInt()));\nList<Node> kids = new ArrayList<>(nodes);\nCollections.reverse(kids);\nNode root = kids.isEmpty() ? null : kids.remove(kids.size() - 1);\nfor (int i = 0; i < nodes.size(); i++) {\n    if (nodes.get(i) == null) continue;\n    if (i * 2 + 1 < nodes.size()) nodes.get(i).left = nodes.get(i * 2 + 1);\n    if (i * 2 + 2 < nodes.size()) nodes.get(i).right = nodes.get(i * 2 + 2);\n}\nint[] best = {Integer.MIN_VALUE};\nclass Dfs {\n    int gain(Node node) {\n        if (node == null) return 0;\n        int l = Math.max(0, gain(node.left));\n        int r = Math.max(0, gain(node.right));\n        best[0] = Math.max(best[0], node.val + l + r);\n        return node.val + Math.max(l, r);\n    }\n}\nnew Dfs().gain(root);\nreturn best[0];",
        cppBody: "std::vector<json> arr = data.value(\"root\", std::vector<json>{});\nstruct Node { int val; Node* left = nullptr; Node* right = nullptr; Node(int v): val(v) {} };\nstd::vector<Node*> nodes(arr.size(), nullptr);\nfor (size_t i = 0; i < arr.size(); i++) if (!arr[i].is_null()) nodes[i] = new Node(arr[i].get<int>());\nfor (size_t i = 0; i < nodes.size(); i++) {\n    if (!nodes[i]) continue;\n    if (i * 2 + 1 < nodes.size()) nodes[i]->left = nodes[i * 2 + 1];\n    if (i * 2 + 2 < nodes.size()) nodes[i]->right = nodes[i * 2 + 2];\n}\nint best = INT_MIN;\nstd::function<int(Node*)> gain = [&](Node* node) -> int {\n    if (!node) return 0;\n    int l = std::max(0, gain(node->left));\n    int r = std::max(0, gain(node->right));\n    best = std::max(best, node->val + l + r);\n    return node->val + std::max(l, r);\n};\nif (!nodes.empty()) gain(nodes[0]);\nreturn best;",
        visibleCases: [
            { input: {"root": [1, 2, 3]}, output: 6, explanation: "Path 2-1-3" },
            { input: {"root": [-10, 9, 20, null, null, 15, 7]}, output: 42 },
        ],
        hiddenCases: [
            { input: {"root": [2, -1]}, output: 2 },
            { input: {"root": [1, -2, -3, 1, 3, -2, null, -1]}, output: 3 },
            { input: {"root": [-3]}, output: -3 },
            { input: {"root": [5, 4, 8, 11, null, 13, 8, null, null, null, null, null, 4, 1]}, output: 45 },
            { input: {"root": [9, -3, null, null, 5]}, output: 11 },
            { input: {"root": [1, 2, null, 3]}, output: 6 },
            { input: {"root": [-2, 1]}, output: 1 },
            { input: {"root": [10, 2, 10, null, null, null, -10]}, output: 22 },
        ],
    },
    {
        num: 95,
        slug: "burst-balloons",
        title: "Burst Balloons",
        difficulty: "HARD",
        topics: ["dynamic-programming"],
        inputFormat: "{ nums: number[] }",
        outputFormat: "number",
        constraints: "1 <= nums.length <= 500; 0 <= nums[i] <= 100",
        hints: ["Pad ends with 1.", "DP on interval last balloon burst."],
        pythonBody: "def solve(data):\n    nums = data.get(\"nums\", [])\n    arr = [1] + nums + [1]\n    n = len(arr)\n    dp = [[0] * n for _ in range(n)]\n    for length in range(3, n + 1):\n        for l in range(0, n - length + 1):\n            r = l + length - 1\n            for k in range(l + 1, r):\n                dp[l][r] = max(dp[l][r], dp[l][k] + dp[k][r] + arr[l] * arr[k] * arr[r])\n    return dp[0][n - 1]",
        javaBody: "JsonArray arrIn = data.has(\"nums\") ? data.getAsJsonArray(\"nums\") : new JsonArray();\nint[] arr = new int[arrIn.size() + 2];\narr[0] = arr[arr.length - 1] = 1;\nfor (int i = 0; i < arrIn.size(); i++) arr[i + 1] = arrIn.get(i).getAsInt();\nint n = arr.length;\nint[][] dp = new int[n][n];\nfor (int len = 3; len <= n; len++) {\n    for (int l = 0; l <= n - len; l++) {\n        int r = l + len - 1;\n        for (int k = l + 1; k < r; k++)\n            dp[l][r] = Math.max(dp[l][r], dp[l][k] + dp[k][r] + arr[l] * arr[k] * arr[r]);\n    }\n}\nreturn dp[0][n - 1];",
        cppBody: "std::vector<int> nums = data.value(\"nums\", std::vector<int>{});\nstd::vector<int> arr = nums;\narr.insert(arr.begin(), 1); arr.push_back(1);\nint n = static_cast<int>(arr.size());\nstd::vector<std::vector<int>> dp(n, std::vector<int>(n));\nfor (int len = 3; len <= n; len++) {\n    for (int l = 0; l <= n - len; l++) {\n        int r = l + len - 1;\n        for (int k = l + 1; k < r; k++)\n            dp[l][r] = std::max(dp[l][r], dp[l][k] + dp[k][r] + arr[l] * arr[k] * arr[r]);\n    }\n}\nreturn dp[0][n - 1];",
        visibleCases: [
            { input: {"nums": [3, 1, 5, 8]}, output: 167, explanation: "167 coins" },
            { input: {"nums": [1, 5]}, output: 10 },
        ],
        hiddenCases: [
            { input: {"nums": [1, 5]}, output: 10 },
            { input: {"nums": [3, 1, 5, 8]}, output: 167 },
            { input: {"nums": [1, 3]}, output: 6 },
            { input: {"nums": [8, 3]}, output: 32 },
            { input: {"nums": [3, 5, 1]}, output: 25 },
            { input: {"nums": [2, 3]}, output: 9 },
            { input: {"nums": [6, 2, 8]}, output: 152 },
            { input: {"nums": [9, 76, 64, 21]}, output: 116718 },
        ],
    },
    {
        num: 96,
        slug: "count-of-smaller-numbers-after-self",
        title: "Count of Smaller Numbers After Self",
        difficulty: "HARD",
        topics: ["binary-search", "bit-manipulation"],
        inputFormat: "{ nums: number[] }",
        outputFormat: "number[]",
        constraints: "1 <= nums.length <= 10^5; -10^4 <= nums[i] <= 10^4",
        hints: ["Process from right to left.", "Insert into sorted structure and count smaller."],
        pythonBody: "def solve(data):\n    from bisect import bisect_left, insort\n    nums = data.get(\"nums\", [])\n    sorted_vals = []\n    out = []\n    for x in reversed(nums):\n        i = bisect_left(sorted_vals, x)\n        out.append(i)\n        insort(sorted_vals, x)\n    return out[::-1]",
        javaBody: "JsonArray arr = data.has(\"nums\") ? data.getAsJsonArray(\"nums\") : new JsonArray();\nList<Integer> sorted = new ArrayList<>();\nList<Integer> out = new ArrayList<>();\nfor (int i = arr.size() - 1; i >= 0; i--) {\n    int x = arr.get(i).getAsInt();\n    int pos = Collections.binarySearch(sorted, x);\n    if (pos < 0) pos = -pos - 1;\n    out.add(0, pos);\n    sorted.add(pos, x);\n}\nreturn out;",
        cppBody: "std::vector<int> nums = data.value(\"nums\", std::vector<int>{});\nstd::vector<int> sorted, out(nums.size());\nfor (int i = static_cast<int>(nums.size()) - 1; i >= 0; i--) {\n    auto it = std::lower_bound(sorted.begin(), sorted.end(), nums[i]);\n    out[i] = static_cast<int>(it - sorted.begin());\n    sorted.insert(it, nums[i]);\n}\nreturn out;",
        visibleCases: [
            { input: {"nums": [5, 2, 6, 1]}, output: [2, 1, 1, 0], explanation: "Counts to the right" },
            { input: {"nums": [-1]}, output: [0] },
        ],
        hiddenCases: [
            { input: {"nums": [-1]}, output: [0] },
            { input: {"nums": [1]}, output: [0] },
            { input: {"nums": [2, 0, 1]}, output: [2, 0, 0] },
            { input: {"nums": [3, 3, 3, 3]}, output: [0, 0, 0, 0] },
            { input: {"nums": [8, 1, 2, 1, 3]}, output: [4, 0, 1, 0, 0] },
            { input: {"nums": [1, 2, 1, 2, 1]}, output: [0, 2, 0, 1, 0] },
            { input: {"nums": [5, 2, 10, 1, 2, 9]}, output: [3, 1, 3, 0, 0, 0] },
            { input: {"nums": [0, 1, 2, 3]}, output: [0, 0, 0, 0] },
        ],
    },
    {
        num: 97,
        slug: "find-median-from-data-stream",
        title: "Find Median from Data Stream",
        difficulty: "HARD",
        topics: ["heap"],
        inputFormat: "{ ops: (\"addNum\"|\"findMedian\")[], args: number[][] }",
        outputFormat: "number[] (one per findMedian)",
        constraints: "At most 5*10^4 operations; values in [-10^5, 10^5]",
        hints: ["Keep max-heap of lower half and min-heap of upper half.", "Balance heap sizes after each add."],
        pythonBody: "def solve(data):\n    import heapq\n    ops = data.get(\"ops\", [])\n    args = data.get(\"args\", [])\n    lo, hi = [], []\n    out = []\n    for op, a in zip(ops, args):\n        if op == \"addNum\":\n            x = a[0]\n            if not lo or x <= -lo[0]:\n                heapq.heappush(lo, -x)\n            else:\n                heapq.heappush(hi, x)\n            if len(lo) > len(hi) + 1:\n                heapq.heappush(hi, -heapq.heappop(lo))\n            elif len(hi) > len(lo):\n                heapq.heappush(lo, -heapq.heappop(hi))\n        else:\n            if len(lo) > len(hi):\n                out.append(float(-lo[0]))\n            else:\n                out.append((-lo[0] + hi[0]) / 2)\n    return out",
        javaBody: "JsonArray opsArr = data.has(\"ops\") ? data.getAsJsonArray(\"ops\") : new JsonArray();\nJsonArray argsArr = data.has(\"args\") ? data.getAsJsonArray(\"args\") : new JsonArray();\nPriorityQueue<Integer> lo = new PriorityQueue<>(Collections.reverseOrder());\nPriorityQueue<Integer> hi = new PriorityQueue<>();\nList<Double> out = new ArrayList<>();\nfor (int i = 0; i < opsArr.size(); i++) {\n    String op = opsArr.get(i).getAsString();\n    if (\"addNum\".equals(op)) {\n        int x = argsArr.get(i).getAsJsonArray().get(0).getAsInt();\n        if (lo.isEmpty() || x <= lo.peek()) lo.offer(x);\n        else hi.offer(x);\n        if (lo.size() > hi.size() + 1) hi.offer(lo.poll());\n        else if (hi.size() > lo.size()) lo.offer(hi.poll());\n    } else {\n        if (lo.size() > hi.size()) out.add(lo.peek().doubleValue());\n        else out.add((lo.peek() + hi.peek()) / 2.0);\n    }\n}\nreturn out;",
        cppBody: "std::vector<std::string> ops = data.value(\"ops\", std::vector<std::string>{});\nstd::vector<std::vector<int>> args = data.value(\"args\", std::vector<std::vector<int>>{});\nstd::priority_queue<int> lo;\nstd::priority_queue<int, std::vector<int>, std::greater<int>> hi;\njson out = json::array();\nfor (size_t i = 0; i < ops.size(); i++) {\n    if (ops[i] == \"addNum\") {\n        int x = args[i][0];\n        if (lo.empty() || x <= lo.top()) lo.push(x);\n        else hi.push(x);\n        if (lo.size() > hi.size() + 1) { hi.push(lo.top()); lo.pop(); }\n        else if (hi.size() > lo.size()) { lo.push(hi.top()); hi.pop(); }\n    } else {\n        if (lo.size() > hi.size()) out.push_back(lo.top());\n        else out.push_back((lo.top() + hi.top()) / 2.0);\n    }\n}\nreturn out;",
        visibleCases: [
            { input: {"ops": ["addNum", "addNum", "findMedian", "addNum", "findMedian"], "args": [[1], [2], [], [3], []]}, output: [1.5, 2], explanation: "Medians 1.5 then 2" },
            { input: {"ops": ["addNum", "findMedian"], "args": [[5], []]}, output: [5] },
        ],
        hiddenCases: [
            { input: {"ops": ["addNum", "addNum", "findMedian"], "args": [[6], [10], []]}, output: [8] },
            { input: {"ops": ["addNum", "addNum", "addNum", "findMedian"], "args": [[1], [2], [3], []]}, output: [2] },
            { input: {"ops": ["addNum", "findMedian", "addNum", "findMedian"], "args": [[2], [], [3], []]}, output: [2, 2.5] },
            { input: {"ops": ["addNum", "addNum", "addNum", "addNum", "findMedian"], "args": [[1], [2], [3], [4], []]}, output: [2.5] },
            { input: {"ops": ["addNum", "addNum", "findMedian", "addNum", "findMedian"], "args": [[-1], [-2], [], [-3], []]}, output: [-1.5, -2] },
            { input: {"ops": ["addNum", "findMedian"], "args": [[100], []]}, output: [100] },
            { input: {"ops": ["addNum", "addNum", "addNum", "findMedian", "addNum", "findMedian"], "args": [[1], [1], [1], [], [1], []]}, output: [1, 1] },
            { input: {"ops": ["addNum", "addNum", "addNum", "addNum", "addNum", "findMedian"], "args": [[1], [2], [3], [4], [5], []]}, output: [3] },
        ],
    },
    {
        num: 98,
        slug: "word-break-ii",
        title: "Word Break II",
        difficulty: "HARD",
        topics: ["dynamic-programming", "backtracking", "trie"],
        inputFormat: "{ s: string, wordDict: string[] }",
        outputFormat: "string[]",
        constraints: "1 <= s.length <= 20; same word may be reused",
        hints: ["DFS with memo on start index.", "Only extend when prefix is a dictionary word."],
        pythonBody: "def solve(data):\n    s = data.get(\"s\", \"\")\n    words = set(data.get(\"wordDict\", []))\n    memo = {}\n    def dfs(i):\n        if i == len(s):\n            return [\"\"]\n        if i in memo:\n            return memo[i]\n        res = []\n        for j in range(i + 1, len(s) + 1):\n            w = s[i:j]\n            if w in words:\n                for rest in dfs(j):\n                    res.append(w if not rest else w + \" \" + rest)\n        memo[i] = res\n        return res\n    return sorted(dfs(0))",
        javaBody: "String s = data.has(\"s\") ? data.get(\"s\").getAsString() : \"\";\nSet<String> words = new HashSet<>();\nif (data.has(\"wordDict\")) for (JsonElement e : data.getAsJsonArray(\"wordDict\")) words.add(e.getAsString());\nMap<Integer, List<String>> memo = new HashMap<>();\nclass Dfs {\n    List<String> go(int i) {\n        if (i == s.length()) return Collections.singletonList(\"\");\n        if (memo.containsKey(i)) return memo.get(i);\n        List<String> res = new ArrayList<>();\n        for (int j = i + 1; j <= s.length(); j++) {\n            String w = s.substring(i, j);\n            if (!words.contains(w)) continue;\n            for (String rest : go(j)) res.add(rest.isEmpty() ? w : w + \" \" + rest);\n        }\n        memo.put(i, res);\n        return res;\n    }\n}\nList<String> ans = new Dfs().go(0);\nCollections.sort(ans);\nreturn ans;",
        cppBody: "std::string s = data.value(\"s\", \"\");\nstd::unordered_set<std::string> words;\nfor (const auto& w : data.value(\"wordDict\", std::vector<std::string>{})) words.insert(w);\nstd::unordered_map<int, std::vector<std::string>> memo;\nstd::function<std::vector<std::string>(int)> dfs = [&](int i) -> std::vector<std::string> {\n    if (i == static_cast<int>(s.size())) return {\"\"};\n    if (memo.count(i)) return memo[i];\n    std::vector<std::string> res;\n    for (int j = i + 1; j <= static_cast<int>(s.size()); j++) {\n        std::string w = s.substr(i, j - i);\n        if (!words.count(w)) continue;\n        for (const auto& rest : dfs(j)) res.push_back(rest.empty() ? w : w + \" \" + rest);\n    }\n    return memo[i] = res;\n};\nauto ans = dfs(0);\nstd::sort(ans.begin(), ans.end());\nreturn ans;",
        visibleCases: [
            { input: {"s": "catsanddog", "wordDict": ["cat", "cats", "and", "sand", "dog"]}, output: ["cat sand dog", "cats and dog"], explanation: "Two sentences" },
            { input: {"s": "pineapplepenapple", "wordDict": ["apple", "pen", "applepen", "pine", "pineapple"]}, output: ["pine apple pen apple", "pine applepen apple", "pineapple pen apple"] },
        ],
        hiddenCases: [
            { input: {"s": "aaaaaaa", "wordDict": ["aaaa", "aaa"]}, output: ["aaa aaaa", "aaaa aaa"] },
            { input: {"s": "a", "wordDict": ["a"]}, output: ["a"] },
            { input: {"s": "ab", "wordDict": ["a", "b", "ab"]}, output: ["a b", "ab"] },
            { input: {"s": "catsanddog", "wordDict": ["cat", "sand", "dog"]}, output: ["cat sand dog"] },
            { input: {"s": "leetcode", "wordDict": ["leet", "code"]}, output: ["leet code"] },
            { input: {"s": "abcd", "wordDict": ["a", "abc", "b", "cd"]}, output: ["a b cd"] },
            { input: {"s": "catsandog", "wordDict": ["cats", "dog", "sand", "and", "cat"]}, output: [] },
            { input: {"s": "ab", "wordDict": ["a", "b"]}, output: ["a b"] },
        ],
    },
    {
        num: 99,
        slug: "palindrome-pairs",
        title: "Palindrome Pairs",
        difficulty: "HARD",
        topics: ["trie", "strings", "hash-table"],
        inputFormat: "{ words: string[] }",
        outputFormat: "number[][] (index pairs)",
        constraints: "1 <= words.length <= 5000; words are unique and non-empty",
        hints: ["Check splits where one part is palindrome.", "Use reverse word lookup."],
        pythonBody: "def solve(data):\n    words = data.get(\"words\", [])\n    def is_pal(s):\n        return s == s[::-1]\n    res = []\n    for i, w in enumerate(words):\n        for j, v in enumerate(words):\n            if i != j and is_pal(w + v):\n                res.append([i, j])\n    return sorted(res)",
        javaBody: "List<String> words = new ArrayList<>();\nif (data.has(\"words\")) for (JsonElement e : data.getAsJsonArray(\"words\")) words.add(e.getAsString());\nList<List<Integer>> res = new ArrayList<>();\nfor (int i = 0; i < words.size(); i++) {\n    for (int j = 0; j < words.size(); j++) {\n        if (i == j) continue;\n        String cat = words.get(i) + words.get(j);\n        int l = 0, r = cat.length() - 1;\n        boolean ok = true;\n        while (l < r) if (cat.charAt(l++) != cat.charAt(r--)) { ok = false; break; }\n        if (ok) res.add(Arrays.asList(i, j));\n    }\n}\nres.sort((a, b) -> a.get(0).equals(b.get(0)) ? a.get(1) - b.get(1) : a.get(0) - b.get(0));\nreturn res;",
        cppBody: "std::vector<std::string> words = data.value(\"words\", std::vector<std::string>{});\nstd::vector<std::vector<int>> res;\nauto isPal = [](const std::string& cat) {\n    int l = 0, r = static_cast<int>(cat.size()) - 1;\n    while (l < r) if (cat[l++] != cat[r--]) return false;\n    return true;\n};\nfor (int i = 0; i < static_cast<int>(words.size()); i++)\n    for (int j = 0; j < static_cast<int>(words.size()); j++)\n        if (i != j && isPal(words[i] + words[j])) res.push_back({i, j});\nstd::sort(res.begin(), res.end());\nreturn res;",
        visibleCases: [
            { input: {"words": ["abcd", "dcba", "lls", "s", "sssll"]}, output: [[0, 1], [1, 0], [2, 4], [3, 2]], explanation: "Palindrome concatenations" },
            { input: {"words": ["bat", "tab", "cat"]}, output: [[0, 1], [1, 0]] },
        ],
        hiddenCases: [
            { input: {"words": ["a", ""]}, output: [[0, 1], [1, 0]] },
            { input: {"words": ["a", "b", "c", "ab", "ac", "aa"]}, output: [[0, 5], [1, 3], [2, 4], [3, 0], [4, 0], [5, 0]] },
            { input: {"words": ["a", "abc", "aba", "ab"]}, output: [[3, 0], [3, 2]] },
            { input: {"words": ["", "a"]}, output: [[0, 1], [1, 0]] },
            { input: {"words": ["a", "b", "c", "d", "e", "f"]}, output: [] },
            { input: {"words": ["noon", "noon"]}, output: [[0, 1], [1, 0]] },
            { input: {"words": ["ll", "lls", "sssll"]}, output: [[0, 2], [1, 0], [1, 2]] },
            { input: {"words": ["a", "b", "aba", "ab"]}, output: [[1, 3], [3, 0], [3, 2]] },
        ],
    },
    {
        num: 100,
        slug: "minimum-cost-to-cut-a-stick",
        title: "Minimum Cost to Cut a Stick",
        difficulty: "HARD",
        topics: ["dynamic-programming", "math"],
        inputFormat: "{ n: number, cuts: number[] }",
        outputFormat: "number",
        constraints: "2 <= n <= 10^6; 1 <= cuts.length <= 100",
        hints: ["Sort cuts with endpoints 0 and n.", "Interval DP on cut positions."],
        pythonBody: "def solve(data):\n    n = data.get(\"n\", 0)\n    cuts = sorted(set(data.get(\"cuts\", [])) | {0, n})\n    m = len(cuts)\n    dp = [[0] * m for _ in range(m)]\n    for length in range(2, m):\n        for i in range(m - length):\n            j = i + length\n            dp[i][j] = float(\"inf\")\n            for k in range(i + 1, j):\n                dp[i][j] = min(dp[i][j], dp[i][k] + dp[k][j] + cuts[j] - cuts[i])\n    return dp[0][m - 1]",
        javaBody: "int n = data.has(\"n\") ? data.get(\"n\").getAsInt() : 0;\nSet<Integer> cutSet = new TreeSet<>();\ncutSet.add(0); cutSet.add(n);\nif (data.has(\"cuts\")) for (JsonElement e : data.getAsJsonArray(\"cuts\")) cutSet.add(e.getAsInt());\nint[] cuts = cutSet.stream().mapToInt(Integer::intValue).toArray();\nint m = cuts.length;\nint[][] dp = new int[m][m];\nfor (int len = 2; len < m; len++) {\n    for (int i = 0; i + len < m; i++) {\n        int j = i + len;\n        dp[i][j] = Integer.MAX_VALUE;\n        for (int k = i + 1; k < j; k++)\n            dp[i][j] = Math.min(dp[i][j], dp[i][k] + dp[k][j] + cuts[j] - cuts[i]);\n    }\n}\nreturn dp[0][m - 1];",
        cppBody: "int n = data.value(\"n\", 0);\nstd::set<int> cutSet{0, n};\nfor (int c : data.value(\"cuts\", std::vector<int>{})) cutSet.insert(c);\nstd::vector<int> cuts(cutSet.begin(), cutSet.end());\nint m = static_cast<int>(cuts.size());\nstd::vector<std::vector<int>> dp(m, std::vector<int>(m));\nfor (int len = 2; len < m; len++) {\n    for (int i = 0; i + len < m; i++) {\n        int j = i + len;\n        dp[i][j] = INT_MAX;\n        for (int k = i + 1; k < j; k++)\n            dp[i][j] = std::min(dp[i][j], dp[i][k] + dp[k][j] + cuts[j] - cuts[i]);\n    }\n}\nreturn dp[0][m - 1];",
        visibleCases: [
            { input: {"n": 7, "cuts": [1, 3, 4, 5]}, output: 16, explanation: "Cost 16" },
            { input: {"n": 5, "cuts": [3, 1, 4]}, output: 10 },
        ],
        hiddenCases: [
            { input: {"n": 9, "cuts": [1, 3, 5, 8]}, output: 21 },
            { input: {"n": 10, "cuts": [2, 4, 6, 8]}, output: 24 },
            { input: {"n": 6, "cuts": [1, 2, 3, 4, 5]}, output: 16 },
            { input: {"n": 8, "cuts": [7, 5, 1, 3]}, output: 19 },
            { input: {"n": 100, "cuts": [25, 50, 75]}, output: 200 },
            { input: {"n": 3, "cuts": [1, 2]}, output: 5 },
            { input: {"n": 50, "cuts": [5, 10, 15, 20, 25, 30, 35, 40, 45]}, output: 170 },
            { input: {"n": 4, "cuts": [1, 3]}, output: 7 },
        ],
    }
];
