import type { ProblemSpec } from "./types.js";

export const BATCH_01_SPECS: ProblemSpec[] = [
    {
        num: 1,
        slug: "two-sum",
        title: "Two Sum",
        difficulty: "EASY",
        topics: ["arrays", "hash-table"],
        inputFormat: "{ nums: number[], target: number }",
        outputFormat: "number[2] indices, or [] if none",
        constraints: "2 <= nums.length <= 10^5; values fit 32-bit signed int.",
        hints: [
            "Store seen values in a hash map.",
            "Check complement before storing current index.",
        ],
        visibleCases: [
            {
                input: { nums: [2, 7, 11, 15], target: 9 },
                output: [0, 1],
                explanation: "2 + 7 = 9",
            },
            {
                input: { nums: [3, 2, 4], target: 6 },
                output: [1, 2],
                explanation: "2 + 4 = 6",
            },
        ],
        hiddenCases: [
            { input: { nums: [3, 3], target: 6 }, output: [0, 1] },
            { input: { nums: [1, 5, 4, 7], target: 8 }, output: [0, 3] },
            { input: { nums: [-1, -2, -3, -4, -5], target: -8 }, output: [2, 4] },
            { input: { nums: [0, 4, 3, 0], target: 0 }, output: [0, 3] },
            { input: { nums: [1, 2, 3, 4], target: 10 }, output: [] },
            { input: { nums: [5, 75, 25], target: 100 }, output: [1, 2] },
            { input: { nums: [2, 5, 5, 11], target: 10 }, output: [1, 2] },
            { input: { nums: [10, -2, 8, 1], target: 9 }, output: [2, 3] },
        ],
    },
    {
        num: 2,
        slug: "valid-parentheses",
        title: "Valid Parentheses",
        difficulty: "EASY",
        topics: ["stack", "strings"],
        inputFormat: "{ s: string }",
        outputFormat: "boolean",
        constraints: "1 <= s.length <= 10^5; chars in ()[]{}",
        hints: [
            "Use a stack.",
            "Map each closing bracket to its opening pair.",
        ],
        visibleCases: [
            {
                input: { s: "()[]{}" },
                output: true,
                explanation: "Every opener closes in order.",
            },
            {
                input: { s: "(]" },
                output: false,
                explanation: "Mismatched pair.",
            },
        ],
        hiddenCases: [
            { input: { s: "" }, output: true },
            { input: { s: "([{}])" }, output: true },
            { input: { s: "([)]" }, output: false },
            { input: { s: "((((" }, output: false },
            { input: { s: "]" }, output: false },
            { input: { s: "{[]}" }, output: true },
            { input: { s: "((()))[]{}" }, output: true },
            { input: { s: "(()" }, output: false },
        ],
    },
    {
        num: 3,
        slug: "best-time-to-buy-and-sell-stock",
        title: "Best Time to Buy and Sell Stock",
        difficulty: "EASY",
        topics: ["arrays", "greedy"],
        inputFormat: "{ prices: number[] }",
        outputFormat: "number",
        constraints: "1 <= prices.length <= 10^5",
        hints: [
            "Track the minimum price seen so far.",
            "Update best profit at each day.",
        ],
        visibleCases: [
            {
                input: { prices: [7, 1, 5, 3, 6, 4] },
                output: 5,
                explanation: "Buy at 1, sell at 6.",
            },
            {
                input: { prices: [7, 6, 4, 3, 1] },
                output: 0,
                explanation: "No profitable trade.",
            },
        ],
        hiddenCases: [
            { input: { prices: [1, 2] }, output: 1 },
            { input: { prices: [2, 1] }, output: 0 },
            { input: { prices: [2, 4, 1] }, output: 2 },
            { input: { prices: [3, 3, 5, 0, 0, 3, 1, 4] }, output: 4 },
            { input: { prices: [1] }, output: 0 },
            { input: { prices: [5, 4, 3, 2, 1, 6] }, output: 5 },
            { input: { prices: [1, 10, 2, 9] }, output: 9 },
            { input: { prices: [9, 8, 7, 6, 5] }, output: 0 },
        ],
    },
    {
        num: 4,
        slug: "valid-palindrome",
        title: "Valid Palindrome",
        difficulty: "EASY",
        topics: ["two-pointers", "strings"],
        inputFormat: "{ s: string }",
        outputFormat: "boolean",
        constraints: "1 <= s.length <= 2*10^5",
        hints: [
            "Use two pointers from both ends.",
            "Skip non-alphanumeric characters.",
        ],
        visibleCases: [
            {
                input: { s: "A man, a plan, a canal: Panama" },
                output: true,
                explanation: "Reads the same forward and backward ignoring case and punctuation.",
            },
            {
                input: { s: "race a car" },
                output: false,
                explanation: "Not a palindrome after filtering.",
            },
        ],
        hiddenCases: [
            { input: { s: " " }, output: true },
            { input: { s: "0P" }, output: false },
            { input: { s: "abba" }, output: true },
            { input: { s: "abc" }, output: false },
            { input: { s: "No lemon, no melon" }, output: true },
            { input: { s: "Was it a car or a cat I saw?" }, output: true },
            { input: { s: "ab_a" }, output: true },
            { input: { s: "ab@a" }, output: true },
        ],
    },
    {
        num: 5,
        slug: "valid-anagram",
        title: "Valid Anagram",
        difficulty: "EASY",
        topics: ["hash-table", "strings"],
        inputFormat: "{ s: string, t: string }",
        outputFormat: "boolean",
        constraints: "1 <= s.length, t.length <= 10^5",
        hints: [
            "Count character frequencies.",
            "Lengths must match first.",
        ],
        visibleCases: [
            {
                input: { s: "anagram", t: "nagaram" },
                output: true,
                explanation: "Same characters with equal frequencies.",
            },
            {
                input: { s: "rat", t: "car" },
                output: false,
                explanation: "Different character sets.",
            },
        ],
        hiddenCases: [
            { input: { s: "", t: "" }, output: true },
            { input: { s: "a", t: "aa" }, output: false },
            { input: { s: "listen", t: "silent" }, output: true },
            { input: { s: "triangle", t: "integral" }, output: true },
            { input: { s: "hello", t: "bello" }, output: false },
            { input: { s: "aabbcc", t: "abcabc" }, output: true },
            { input: { s: "xxy", t: "xyx" }, output: true },
            { input: { s: "xxy", t: "xyz" }, output: false },
        ],
    },
    {
        num: 6,
        slug: "climbing-stairs",
        title: "Climbing Stairs",
        difficulty: "EASY",
        topics: ["dynamic-programming", "math"],
        inputFormat: "{ n: number }",
        outputFormat: "number",
        constraints: "1 <= n <= 45",
        hints: [
            "Ways to reach step n equal ways(n-1) + ways(n-2).",
            "Keep only the last two states.",
        ],
        visibleCases: [
            {
                input: { n: 2 },
                output: 2,
                explanation: "1+1 or 2.",
            },
            {
                input: { n: 3 },
                output: 3,
                explanation: "1+1+1, 1+2, or 2+1.",
            },
        ],
        hiddenCases: [
            { input: { n: 1 }, output: 1 },
            { input: { n: 4 }, output: 5 },
            { input: { n: 5 }, output: 8 },
            { input: { n: 6 }, output: 13 },
            { input: { n: 7 }, output: 21 },
            { input: { n: 8 }, output: 34 },
            { input: { n: 10 }, output: 89 },
            { input: { n: 12 }, output: 233 },
        ],
    },
    {
        num: 7,
        slug: "binary-search",
        title: "Binary Search",
        difficulty: "EASY",
        topics: ["binary-search", "arrays"],
        inputFormat: "{ nums: number[], target: number }",
        outputFormat: "number",
        constraints: "nums sorted ascending; up to 10^5 elements",
        hints: [
            "Maintain [lo, hi] boundaries.",
            "Use mid = lo + (hi-lo)//2.",
        ],
        visibleCases: [
            {
                input: { nums: [-1, 0, 3, 5, 9, 12], target: 9 },
                output: 4,
                explanation: "9 is at index 4.",
            },
            {
                input: { nums: [-1, 0, 3, 5, 9, 12], target: 2 },
                output: -1,
                explanation: "2 is not in the array.",
            },
        ],
        hiddenCases: [
            { input: { nums: [1], target: 1 }, output: 0 },
            { input: { nums: [1], target: 0 }, output: -1 },
            { input: { nums: [1, 3, 5, 7], target: 7 }, output: 3 },
            { input: { nums: [1, 3, 5, 7], target: 1 }, output: 0 },
            { input: { nums: [1, 3, 5, 7], target: 4 }, output: -1 },
            { input: { nums: [], target: 4 }, output: -1 },
            { input: { nums: [-5, -2, 0, 10], target: -2 }, output: 1 },
            { input: { nums: [-5, -2, 0, 10], target: 11 }, output: -1 },
        ],
    },
    {
        num: 8,
        slug: "contains-duplicate",
        title: "Contains Duplicate",
        difficulty: "EASY",
        topics: ["arrays", "hash-table"],
        inputFormat: "{ nums: number[] }",
        outputFormat: "boolean",
        constraints: "1 <= nums.length <= 10^5; values fit 32-bit signed int.",
        hints: [
            "Track values you have already seen.",
            "A set makes duplicate detection O(1).",
        ],
        visibleCases: [
            {
                input: { nums: [1, 2, 3, 1] },
                output: true,
                explanation: "1 appears twice.",
            },
            {
                input: { nums: [1, 2, 3, 4] },
                output: false,
                explanation: "All elements are distinct.",
            },
        ],
        hiddenCases: [
            { input: { nums: [1, 1] }, output: true },
            { input: { nums: [1] }, output: false },
            { input: { nums: [] }, output: false },
            { input: { nums: [1, 2, 3, 4, 5, 6, 7, 8, 9, 1] }, output: true },
            { input: { nums: [-1, -2, -3, -1] }, output: true },
            { input: { nums: [0, 0] }, output: true },
            { input: { nums: [5, 5, 5] }, output: true },
            { input: { nums: [10, 20, 30, 40] }, output: false },
        ],
    },
    {
        num: 9,
        slug: "isomorphic-strings",
        title: "Isomorphic Strings",
        difficulty: "EASY",
        topics: ["hash-table", "strings"],
        inputFormat: "{ s: string, t: string }",
        outputFormat: "boolean",
        constraints: "1 <= s.length, t.length <= 10^5; s and t have equal length",
        hints: [
            "Map characters from s to t and back.",
            "Reject if any mapping conflicts.",
        ],
        visibleCases: [
            {
                input: { s: "egg", t: "add" },
                output: true,
                explanation: "e->a and g->d preserves order.",
            },
            {
                input: { s: "foo", t: "bar" },
                output: false,
                explanation: "o cannot map to both a and r.",
            },
        ],
        hiddenCases: [
            { input: { s: "", t: "" }, output: true },
            { input: { s: "a", t: "a" }, output: true },
            { input: { s: "paper", t: "title" }, output: true },
            { input: { s: "badc", t: "baba" }, output: false },
            { input: { s: "ab", t: "aa" }, output: false },
            { input: { s: "abc", t: "def" }, output: true },
            { input: { s: "13", t: "42" }, output: true },
            { input: { s: "abba", t: "cdce" }, output: false },
        ],
    },
    {
        num: 10,
        slug: "ransom-note",
        title: "Ransom Note",
        difficulty: "EASY",
        topics: ["hash-table", "strings"],
        inputFormat: "{ ransomNote: string, magazine: string }",
        outputFormat: "boolean",
        constraints: "1 <= ransomNote.length, magazine.length <= 10^5",
        hints: [
            "Count letters available in magazine.",
            "Decrement counts as you use each ransom letter.",
        ],
        visibleCases: [
            {
                input: { ransomNote: "a", magazine: "b" },
                output: false,
                explanation: "Magazine has no 'a'.",
            },
            {
                input: { ransomNote: "aa", magazine: "aab" },
                output: true,
                explanation: "Magazine has two a's.",
            },
        ],
        hiddenCases: [
            { input: { ransomNote: "", magazine: "abc" }, output: true },
            { input: { ransomNote: "aa", magazine: "ab" }, output: false },
            { input: { ransomNote: "aa", magazine: "aa" }, output: true },
            { input: { ransomNote: "aab", magazine: "baa" }, output: true },
            { input: { ransomNote: "xyz", magazine: "xy" }, output: false },
            { input: { ransomNote: "a", magazine: "a" }, output: true },
            { input: { ransomNote: "bg", magazine: "efjdfdfjhhaiiahbaiaeahxcaaief" }, output: false },
            { input: { ransomNote: "apple", magazine: "aple" }, output: false },
        ],
    },
    {
        num: 11,
        slug: "first-bad-version",
        title: "First Bad Version",
        difficulty: "EASY",
        topics: ["binary-search"],
        inputFormat: "{ n: number, bad: number }",
        outputFormat: "number",
        constraints: "1 <= bad <= n <= 2^31 - 1; versions after the first bad are also bad",
        hints: [
            "Binary search on version numbers 1..n.",
            "If mid is bad, search left including mid.",
        ],
        visibleCases: [
            {
                input: { n: 5, bad: 4 },
                output: 4,
                explanation: "Version 4 is the first bad version.",
            },
            {
                input: { n: 1, bad: 1 },
                output: 1,
                explanation: "Only version is bad.",
            },
        ],
        hiddenCases: [
            { input: { n: 10, bad: 10 }, output: 10 },
            { input: { n: 10, bad: 1 }, output: 1 },
            { input: { n: 2126753390, bad: 1702766719 }, output: 1702766719 },
            { input: { n: 2, bad: 2 }, output: 2 },
            { input: { n: 2, bad: 1 }, output: 1 },
            { input: { n: 100, bad: 50 }, output: 50 },
            { input: { n: 7, bad: 3 }, output: 3 },
            { input: { n: 8, bad: 8 }, output: 8 },
        ],
    },
    {
        num: 12,
        slug: "sqrtx",
        title: "Sqrt(x)",
        difficulty: "EASY",
        topics: ["math", "binary-search"],
        inputFormat: "{ x: number }",
        outputFormat: "number",
        constraints: "0 <= x <= 2^31 - 1",
        hints: [
            "Binary search on answer y in [0, x].",
            "Keep the largest y with y * y <= x.",
        ],
        visibleCases: [
            {
                input: { x: 4 },
                output: 2,
                explanation: "2 * 2 = 4.",
            },
            {
                input: { x: 8 },
                output: 2,
                explanation: "2^2 = 4 <= 8 and 3^2 = 9 > 8.",
            },
        ],
        hiddenCases: [
            { input: { x: 0 }, output: 0 },
            { input: { x: 1 }, output: 1 },
            { input: { x: 9 }, output: 3 },
            { input: { x: 15 }, output: 3 },
            { input: { x: 16 }, output: 4 },
            { input: { x: 2147483647 }, output: 46340 },
            { input: { x: 100 }, output: 10 },
            { input: { x: 26 }, output: 5 },
        ],
    },
    {
        num: 13,
        slug: "find-peak-element",
        title: "Find Peak Element",
        difficulty: "EASY",
        topics: ["binary-search", "arrays"],
        inputFormat: "{ nums: number[] }",
        outputFormat: "number",
        constraints: "1 <= nums.length <= 10^5; nums[i] != nums[i+1] for valid i",
        hints: [
            "Compare nums[mid] with nums[mid+1].",
            "Move toward the larger neighbor.",
        ],
        visibleCases: [
            {
                input: { nums: [1, 2, 3, 1] },
                output: 2,
                explanation: "3 is a peak at index 2.",
            },
            {
                input: { nums: [1, 2, 1, 3, 5, 6, 4] },
                output: 5,
                explanation: "6 is a peak at index 5.",
            },
        ],
        hiddenCases: [
            { input: { nums: [1] }, output: 0 },
            { input: { nums: [1, 2] }, output: 1 },
            { input: { nums: [2, 1] }, output: 0 },
            { input: { nums: [1, 2, 3, 4, 5] }, output: 4 },
            { input: { nums: [5, 4, 3, 2, 1] }, output: 0 },
            { input: { nums: [1, 3, 2] }, output: 1 },
            { input: { nums: [3, 2, 1, 4, 5, 6, 7, 8, 9, 1] }, output: 8 },
            { input: { nums: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0] }, output: 0 },
        ],
    },
    {
        num: 14,
        slug: "search-insert-position",
        title: "Search Insert Position",
        difficulty: "EASY",
        topics: ["binary-search", "arrays"],
        inputFormat: "{ nums: number[], target: number }",
        outputFormat: "number",
        constraints: "nums sorted ascending; 1 <= nums.length <= 10^4",
        hints: [
            "Binary search for target.",
            "If absent, lo ends at the insert position.",
        ],
        visibleCases: [
            {
                input: { nums: [1, 3, 5, 6], target: 5 },
                output: 2,
                explanation: "5 is found at index 2.",
            },
            {
                input: { nums: [1, 3, 5, 6], target: 2 },
                output: 1,
                explanation: "2 would be inserted at index 1.",
            },
        ],
        hiddenCases: [
            { input: { nums: [1, 3, 5, 6], target: 7 }, output: 4 },
            { input: { nums: [1, 3, 5, 6], target: 0 }, output: 0 },
            { input: { nums: [1], target: 1 }, output: 0 },
            { input: { nums: [1], target: 0 }, output: 0 },
            { input: { nums: [1, 3], target: 2 }, output: 1 },
            { input: { nums: [1, 3], target: 4 }, output: 2 },
            { input: { nums: [1, 3, 5, 7], target: 6 }, output: 3 },
            { input: { nums: [1, 3, 5, 7], target: 3 }, output: 1 },
        ],
    },
    {
        num: 15,
        slug: "longest-common-prefix",
        title: "Longest Common Prefix",
        difficulty: "EASY",
        topics: ["strings"],
        inputFormat: "{ strs: string[] }",
        outputFormat: "string",
        constraints: "1 <= strs.length <= 200; 0 <= strs[i].length <= 200",
        hints: [
            "Start with the first string as prefix.",
            "Shrink prefix until all strings share it.",
        ],
        visibleCases: [
            {
                input: { strs: ["flower", "flow", "flight"] },
                output: "fl",
                explanation: "fl is shared by all three strings.",
            },
            {
                input: { strs: ["dog", "racecar", "car"] },
                output: "",
                explanation: "No common prefix.",
            },
        ],
        hiddenCases: [
            { input: { strs: ["a"] }, output: "a" },
            { input: { strs: ["ab", "a"] }, output: "a" },
            { input: { strs: ["", "b"] }, output: "" },
            { input: { strs: ["abab", "aba", "abc"] }, output: "ab" },
            { input: { strs: ["reflower", "flow", "flight"] }, output: "" },
            { input: { strs: ["c", "c"] }, output: "c" },
            { input: { strs: ["interspecies", "interstellar", "interstate"] }, output: "inters" },
            { input: { strs: ["throne", "throne"] }, output: "throne" },
        ],
    },
    {
        num: 16,
        slug: "implement-strstr",
        title: "Implement strStr",
        difficulty: "EASY",
        topics: ["strings", "two-pointers"],
        inputFormat: "{ haystack: string, needle: string }",
        outputFormat: "number",
        constraints: "0 <= haystack.length, needle.length <= 10^4",
        hints: [
            "Empty needle occurs at index 0.",
            "Check each start index in haystack.",
        ],
        visibleCases: [
            {
                input: { haystack: "sadbutsad", needle: "sad" },
                output: 0,
                explanation: "sad starts at index 0.",
            },
            {
                input: { haystack: "leetcode", needle: "leeto" },
                output: -1,
                explanation: "leeto is not a substring.",
            },
        ],
        hiddenCases: [
            { input: { haystack: "", needle: "" }, output: 0 },
            { input: { haystack: "a", needle: "" }, output: 0 },
            { input: { haystack: "hello", needle: "ll" }, output: 2 },
            { input: { haystack: "aaaa", needle: "bba" }, output: -1 },
            { input: { haystack: "mississippi", needle: "issip" }, output: 4 },
            { input: { haystack: "abc", needle: "c" }, output: 2 },
            { input: { haystack: "abc", needle: "abcd" }, output: -1 },
            { input: { haystack: "abcabc", needle: "cab" }, output: 2 },
        ],
    },
    {
        num: 17,
        slug: "reverse-words-in-a-string-iii",
        title: "Reverse Words in a String III",
        difficulty: "EASY",
        topics: ["strings", "two-pointers"],
        inputFormat: "{ s: string }",
        outputFormat: "string",
        constraints: "1 <= s.length <= 5*10^4; s contains printable ASCII and spaces",
        hints: [
            "Reverse each word in place.",
            "Single spaces separate words.",
        ],
        visibleCases: [
            {
                input: { s: "Let's take LeetCode contest" },
                output: "s'teL ekat edoCteeL tsetnoc",
                explanation: "Each word is reversed in place.",
            },
            {
                input: { s: "God Ding" },
                output: "doG gniD",
                explanation: "Two words reversed separately.",
            },
        ],
        hiddenCases: [
            { input: { s: "a" }, output: "a" },
            { input: { s: "ab" }, output: "ba" },
            { input: { s: "a good   example" }, output: "a doog   elpmaxe" },
            { input: { s: "hello" }, output: "olleh" },
            { input: { s: "hi there" }, output: "ih ereht" },
            { input: { s: "L" }, output: "L" },
            { input: { s: "test word" }, output: "tset drow" },
            { input: { s: "abc def ghi" }, output: "cba fed ihg" },
        ],
    },
    {
        num: 18,
        slug: "majority-element",
        title: "Majority Element",
        difficulty: "EASY",
        topics: ["arrays", "hash-table"],
        inputFormat: "{ nums: number[] }",
        outputFormat: "number",
        constraints: "1 <= nums.length <= 5*10^4; majority element always exists",
        hints: [
            "Boyer-Moore tracks a candidate and count.",
            "Cancel equal pairs; survivor is majority.",
        ],
        visibleCases: [
            {
                input: { nums: [3, 2, 3] },
                output: 3,
                explanation: "3 appears more than half the time.",
            },
            {
                input: { nums: [2, 2, 1, 1, 1, 2, 2] },
                output: 2,
                explanation: "2 is the majority element.",
            },
        ],
        hiddenCases: [
            { input: { nums: [1] }, output: 1 },
            { input: { nums: [6, 5, 5] }, output: 5 },
            { input: { nums: [1, 1, 1, 2] }, output: 1 },
            { input: { nums: [4, 4, 4, 2, 4] }, output: 4 },
            { input: { nums: [7, 7, 7, 7, 1, 7] }, output: 7 },
            { input: { nums: [10, 10, 10, 10, 10, 5] }, output: 10 },
            { input: { nums: [1, 2, 1, 1] }, output: 1 },
            { input: { nums: [5, 5, 5, 5, 6, 5] }, output: 5 },
        ],
    },
    {
        num: 19,
        slug: "move-zeroes",
        title: "Move Zeroes",
        difficulty: "EASY",
        topics: ["arrays", "two-pointers"],
        inputFormat: "{ nums: number[] }",
        outputFormat: "number[]",
        constraints: "1 <= nums.length <= 10^4; values fit 32-bit signed int",
        hints: [
            "Write non-zero values from left to right.",
            "Fill remaining positions with zero.",
        ],
        visibleCases: [
            {
                input: { nums: [0, 1, 0, 3, 12] },
                output: [1, 3, 12, 0, 0],
                explanation: "Non-zeros shift left preserving order.",
            },
            {
                input: { nums: [0] },
                output: [0],
                explanation: "Single zero stays in place.",
            },
        ],
        hiddenCases: [
            { input: { nums: [1] }, output: [1] },
            { input: { nums: [1, 0] }, output: [1, 0] },
            { input: { nums: [0, 0, 1] }, output: [1, 0, 0] },
            { input: { nums: [4, 2, 4, 0, 0, 3, 0, 5, 1, 0] }, output: [4, 2, 4, 3, 5, 1, 0, 0, 0, 0] },
            { input: { nums: [0, 0, 0] }, output: [0, 0, 0] },
            { input: { nums: [2, 1] }, output: [2, 1] },
            { input: { nums: [0, 2, 0, 0, 1] }, output: [2, 1, 0, 0, 0] },
            { input: { nums: [1, 2, 3] }, output: [1, 2, 3] },
        ],
    },
    {
        num: 20,
        slug: "remove-duplicates-from-sorted-array",
        title: "Remove Duplicates from Sorted Array",
        difficulty: "EASY",
        topics: ["arrays", "two-pointers"],
        inputFormat: "{ nums: number[] }",
        outputFormat: "number",
        constraints: "1 <= nums.length <= 3*10^4; nums sorted non-decreasing",
        hints: [
            "Use write pointer for unique values.",
            "Skip duplicates while scanning.",
        ],
        visibleCases: [
            {
                input: { nums: [1, 1, 2] },
                output: 2,
                explanation: "Unique prefix is [1, 2].",
            },
            {
                input: { nums: [0, 0, 1, 1, 1, 2, 2, 3, 3, 4] },
                output: 5,
                explanation: "Five unique values in order.",
            },
        ],
        hiddenCases: [
            { input: { nums: [1] }, output: 1 },
            { input: { nums: [1, 1, 1, 1] }, output: 1 },
            { input: { nums: [1, 2, 3] }, output: 3 },
            { input: { nums: [1, 2, 2] }, output: 2 },
            { input: { nums: [-1, 0, 0, 0, 0, 3, 3] }, output: 3 },
            { input: { nums: [1, 1, 2, 2, 3] }, output: 3 },
            { input: { nums: [5, 5, 6, 7, 7, 8] }, output: 4 },
            { input: { nums: [0, 0, 0, 1] }, output: 2 },
        ],
    },
    {
        num: 21,
        slug: "merge-sorted-array",
        title: "Merge Sorted Array",
        difficulty: "EASY",
        topics: ["arrays", "two-pointers"],
        inputFormat: "{ nums1: number[], m: number, nums2: number[], n: number }",
        outputFormat: "number[]",
        constraints: "nums1.length == m + n; 0 <= m, n <= 200",
        hints: [
            "Merge from the back to avoid overwriting.",
            "Compare largest remaining elements.",
        ],
        visibleCases: [
            {
                input: { nums1: [1, 2, 3, 0, 0, 0], m: 3, nums2: [2, 5, 6], n: 3 },
                output: [1, 2, 2, 3, 5, 6],
                explanation: "Merged sorted result in nums1.",
            },
            {
                input: { nums1: [1], m: 1, nums2: [], n: 0 },
                output: [1],
                explanation: "nums2 is empty.",
            },
        ],
        hiddenCases: [
            { input: { nums1: [0], m: 0, nums2: [1], n: 1 }, output: [1] },
            { input: { nums1: [2, 0], m: 1, nums2: [1], n: 1 }, output: [1, 2] },
            { input: { nums1: [4, 5, 6, 0, 0, 0], m: 3, nums2: [1, 2, 3], n: 3 }, output: [1, 2, 3, 4, 5, 6] },
            { input: { nums1: [1, 2, 4, 5, 6, 0], m: 5, nums2: [3], n: 1 }, output: [1, 2, 3, 4, 5, 6] },
            { input: { nums1: [1, 0], m: 1, nums2: [2], n: 1 }, output: [1, 2] },
            { input: { nums1: [0, 0, 0], m: 0, nums2: [1, 2, 3], n: 3 }, output: [1, 2, 3] },
            { input: { nums1: [1, 2, 3, 0, 0], m: 3, nums2: [4, 5], n: 2 }, output: [1, 2, 3, 4, 5] },
            { input: { nums1: [2, 0, 0], m: 1, nums2: [1, 3], n: 2 }, output: [1, 2, 3] },
        ],
    },
    {
        num: 22,
        slug: "roman-to-integer",
        title: "Roman to Integer",
        difficulty: "EASY",
        topics: ["strings", "math"],
        inputFormat: "{ s: string }",
        outputFormat: "number",
        constraints: "1 <= s.length <= 15; s is a valid Roman numeral",
        hints: [
            "Map each symbol to a value.",
            "Subtract when a smaller value precedes a larger one.",
        ],
        visibleCases: [
            {
                input: { s: "III" },
                output: 3,
                explanation: "I + I + I = 3.",
            },
            {
                input: { s: "LVIII" },
                output: 58,
                explanation: "L + V + III = 58.",
            },
        ],
        hiddenCases: [
            { input: { s: "IV" }, output: 4 },
            { input: { s: "IX" }, output: 9 },
            { input: { s: "MCMXCIV" }, output: 1994 },
            { input: { s: "X" }, output: 10 },
            { input: { s: "XL" }, output: 40 },
            { input: { s: "XC" }, output: 90 },
            { input: { s: "CD" }, output: 400 },
            { input: { s: "CM" }, output: 900 },
        ],
    },
    {
        num: 23,
        slug: "single-number",
        title: "Single Number",
        difficulty: "EASY",
        topics: ["bit-manipulation", "arrays"],
        inputFormat: "{ nums: number[] }",
        outputFormat: "number",
        constraints: "1 <= nums.length <= 3*10^4; exactly one element appears once",
        hints: [
            "XOR pairs cancel out.",
            "XOR all numbers together.",
        ],
        visibleCases: [
            {
                input: { nums: [2, 2, 1] },
                output: 1,
                explanation: "1 appears once.",
            },
            {
                input: { nums: [4, 1, 2, 1, 2] },
                output: 4,
                explanation: "4 appears once.",
            },
        ],
        hiddenCases: [
            { input: { nums: [1] }, output: 1 },
            { input: { nums: [0, 1, 0] }, output: 1 },
            { input: { nums: [7, 3, 5, 3, 5] }, output: 7 },
            { input: { nums: [-1, -1, -2] }, output: -2 },
            { input: { nums: [10, 20, 10] }, output: 20 },
            { input: { nums: [99, 42, 99] }, output: 42 },
            { input: { nums: [6, 6, 8, 8, 9] }, output: 9 },
            { input: { nums: [100000, 200000, 100000] }, output: 200000 },
        ],
    },
    {
        num: 24,
        slug: "missing-number",
        title: "Missing Number",
        difficulty: "EASY",
        topics: ["math", "bit-manipulation"],
        inputFormat: "{ nums: number[] }",
        outputFormat: "number",
        constraints: "n == nums.length; nums has n distinct values in [0, n]",
        hints: [
            "Sum of 0..n minus sum(nums).",
            "XOR index with each value also works.",
        ],
        visibleCases: [
            {
                input: { nums: [3, 0, 1] },
                output: 2,
                explanation: "2 is missing from [0, 3].",
            },
            {
                input: { nums: [0, 1] },
                output: 2,
                explanation: "2 is missing from [0, 2].",
            },
        ],
        hiddenCases: [
            { input: { nums: [9, 6, 4, 2, 3, 5, 7, 0, 1] }, output: 8 },
            { input: { nums: [0] }, output: 1 },
            { input: { nums: [1] }, output: 0 },
            { input: { nums: [2, 0] }, output: 1 },
            { input: { nums: [4, 0, 1, 2] }, output: 3 },
            { input: { nums: [5, 0, 1, 2, 3] }, output: 4 },
            { input: { nums: [1, 2, 3, 4, 5, 6, 7, 8, 9] }, output: 0 },
            { input: { nums: [0, 2, 3] }, output: 1 },
        ],
    },
    {
        num: 25,
        slug: "fibonacci-number",
        title: "Fibonacci Number",
        difficulty: "EASY",
        topics: ["dynamic-programming", "math"],
        inputFormat: "{ n: number }",
        outputFormat: "number",
        constraints: "0 <= n <= 30",
        hints: [
            "F(0)=0, F(1)=1, F(n)=F(n-1)+F(n-2).",
            "Iterate with two variables.",
        ],
        visibleCases: [
            {
                input: { n: 2 },
                output: 1,
                explanation: "F(2) = F(1) + F(0) = 1.",
            },
            {
                input: { n: 3 },
                output: 2,
                explanation: "F(3) = F(2) + F(1) = 2.",
            },
        ],
        hiddenCases: [
            { input: { n: 0 }, output: 0 },
            { input: { n: 1 }, output: 1 },
            { input: { n: 4 }, output: 3 },
            { input: { n: 5 }, output: 5 },
            { input: { n: 6 }, output: 8 },
            { input: { n: 7 }, output: 13 },
            { input: { n: 10 }, output: 55 },
            { input: { n: 12 }, output: 144 },
        ],
    },
];
